Repository argilla-io/argilla, pull requests merged in 2021-08, with the labels that each got.

#262 Fixing Kglab empty cell
  docs/tutorials/03-kglab_pytorch_geometric.ipynb
Labels: documentation

#254 Supported Tasks Example Article
  docs/getting_started/concepts.rst
  docs/getting_started/supported_tasks.rst
  docs/guides/task_examples.ipynb
  docs/index.rst
Labels: documentation

#275 refactor(search): simplify query text search model
  src/rubrix/sdk/models/__init__.py
  src/rubrix/sdk/models/text_classification_query.py
  src/rubrix/sdk/models/text_classification_query_query_inputs.py
  src/rubrix/sdk/models/token_classification_query.py
  src/rubrix/sdk/models/token_classification_query_query_text.py
  src/rubrix/server/tasks/commons/es_helpers.py
  src/rubrix/server/tasks/text_classification/api/model.py
  src/rubrix/server/tasks/token_classification/api/model.py
Labels: app, breaking changes

#241 Tutorial: 🧐 Using Rubrix to find label errors with cleanlab
  docs/index.rst
  docs/tutorials/07-find_label_errors.ipynb
  docs/tutorials/img/find_label_errors/test_sample_examples.png
  docs/tutorials/img/find_label_errors/train_sample_examples.png
Labels: documentation

#263 feat(app): copy datasets feature
  .github/workflows/ci.yml
  setup.cfg
  src/rubrix/__init__.py
  src/rubrix/client/__init__.py
  src/rubrix/sdk/api/datasets/copy_dataset.py
  src/rubrix/sdk/models/copy_dataset_request.py
  src/rubrix/sdk/models/copy_dataset_request_metadata.py
  src/rubrix/sdk/models/copy_dataset_request_tags.py
  src/rubrix/server/commons/errors.py
  src/rubrix/server/commons/es_wrapper.py
  src/rubrix/server/datasets/api.py
  src/rubrix/server/datasets/dao.py
  src/rubrix/server/datasets/model.py
  src/rubrix/server/datasets/service.py
  tests/client/test_client.py
Labels: breaking changes
