Repository argilla-io/argilla, pull requests merged in 2021-11, with the labels that each got.

#636 [QA] text classification labels
  frontend/components/core/ReTag.vue
  frontend/components/text-classifier/results/ClassifierAnnotationArea.vue
  frontend/components/text-classifier/results/ClassifierAnnotationButton.vue
  frontend/components/text-classifier/results/ClassifierExplorationArea.vue
  frontend/components/text-classifier/results/LabelPill.vue
  frontend/components/text-classifier/results/LabelSearch.vue
  frontend/components/text-classifier/results/RecordTextClassification.vue
  frontend/database/modules/datasets.js
  frontend/models/DatasetViewSettings.js
Labels: app

#641 NoRecordsFoundError when rb.load results in empty list in WeakLabels
  docs/reference/python/python_labeling.rst
  src/rubrix/labeling/text_classification/label_models.py
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_label_models.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: labeling

#655 fix(search): prevent ignore zeros for aggregation result keys
  src/rubrix/server/commons/es_helpers.py
Labels: bug

#660 refactor(user): bypass workspace for super users
  src/rubrix/server/security/model.py
  tests/server/security/test_model.py
Labels: bug

#670 [Labeling] Change default behavior for Snorkel.fit
  src/rubrix/labeling/text_classification/label_models.py
  tests/labeling/text_classification/test_label_models.py
Labels: labeling

#678 fix(server): metadata keys with empty meta will be omitted
  src/rubrix/server/commons/helpers.py
  src/rubrix/server/tasks/commons/api/model.py
  tests/functional_tests/test_log_for_text_classification.py
Labels: v0.6.1

#680 fix(docs): .rubrix_* -> .rubrix*
  docs/getting_started/advanced_setup_guides.rst
Labels: v0.6.1

#693 [Labeling] Throw error when encountering duplicated rule names
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: labeling

#649 [Docs] First attempt to devise a testing workflow for the tutorials
  .github/workflows/tutorials.yml
  docs/tutorials/05-active_learning.ipynb
Labels: documentation

#709 feat(metrics): improve common dataset metrics
  src/rubrix/metrics/commons.py
  src/rubrix/server/tasks/commons/metrics/commons.py
  tests/client/test_models.py
  tests/metrics/test_common_metrics.py
Labels: enhancement

#578 [Docs] Add WeaSEL example to weak supervision guide
  docs/guides/weak-supervision.ipynb
Labels: documentation, labeling

#720 [Tutorials] Remove kglab tutorial
  docs/index.rst
  docs/tutorials/03-kglab_pytorch_geometric.ipynb
Labels: documentation

#727 [Tutorials] Add tutorials to tutorials test action
  .github/workflows/tutorials.yml
  docs/tutorials/08-error_analysis_using_loss.ipynb
  docs/tutorials/09-automatic_fastapi_log.ipynb
  docs/tutorials/weak-supervision-with-rubrix.ipynb
Labels: documentation

#729 [Labeling] Fix WeakLabels.change_mapping method
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: bug, labeling

#732 [Metrics] Fixes F1 key names of the text classification metrics
  src/rubrix/server/tasks/text_classification/metrics.py
  tests/metrics/test_text_classification.py
Labels: bug
