Repository argilla-io/argilla, pull requests merged in 2021-12, with the labels that each got.

#755 [Labeling] Add FlyingSquid label model
  docs/guides/weak-supervision.ipynb
  docs/reference/python/python_labeling.rst
  environment_dev.yml
  src/rubrix/labeling/text_classification/__init__.py
  src/rubrix/labeling/text_classification/label_models.py
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_label_models.py
Labels: labeling

#770 [Requirements] Require python>=3.7
  docs/getting_started/setup&installation.rst
  setup.cfg
Labels: bug

#789 feat(server): rubrix namespaces for elasticsearch indices
  src/rubrix/server/commons/es_settings.py
  src/rubrix/server/commons/settings.py
  tests/server/commons/test_settings.py
Labels: enhancement

#802 fix(log): check multi-label integrity without search aggregations
  src/rubrix/server/tasks/text_classification/service/service.py
Labels: bug, server

#812 Fix token alignment on CreationTokenClassificationRecord
  src/rubrix/server/tasks/token_classification/api/model.py
  tests/server/token_classification/test_model.py
Labels: bug, v0.7.0

#775 [LabelErrors] Add find_label_errors method
  docs/reference/python/python_labeling.rst
  docs/tutorials/find_label_errors.ipynb
  environment_dev.yml
  src/rubrix/labeling/text_classification/__init__.py
  src/rubrix/labeling/text_classification/label_errors.py
  tests/client/test_rubrix_client.py
  tests/labeling/text_classification/conftest.py
  tests/labeling/text_classification/resources/weak-supervision-guide-matrix.npy
  tests/labeling/text_classification/test_label_errors.py
Labels: labeling

#834 fix(ui): remove workspace home from code snippet api url
  frontend/components/commons/datasets-list/DatasetsEmpty.vue
Labels: bug

#837 feat (search): allow to filtering record metrics fields in search
  src/rubrix/server/commons/api.py
  src/rubrix/server/tasks/commons/dao/dao.py
  src/rubrix/server/tasks/text2text/api/api.py
  src/rubrix/server/tasks/text2text/service/service.py
  src/rubrix/server/tasks/text_classification/api/api.py
  src/rubrix/server/tasks/text_classification/service/service.py
  src/rubrix/server/tasks/token_classification/api/api.py
  src/rubrix/server/tasks/token_classification/service/service.py
  tests/server/token_classification/test_api.py
Labels: enhancement

#836 [LabelModel] Improve Snorkel to not modify the passed in WeakLabels object
  src/rubrix/labeling/text_classification/label_models.py
  tests/labeling/text_classification/test_label_models.py
Labels: labeling

#833 [Tutorials] Add the new find_label_errors tutorial
  docs/conf.py
  docs/index.rst
  docs/tutorials/06-find_label_errors.ipynb
  docs/tutorials/find_label_errors.ipynb
  docs/tutorials/find_label_errors/sort.png
  docs/tutorials/find_label_errors/tldr.mp4
  src/rubrix/labeling/text_classification/label_errors.py
Labels: documentation, labeling

#842 [Tutorials] Typo fix in find label errors tutorial
  docs/tutorials/find_label_errors.ipynb
Labels: documentation

#843 fix(rules): prevent division by zero
  src/rubrix/client/sdk/text_classification/models.py
  src/rubrix/labeling/text_classification/rule.py
  src/rubrix/server/tasks/text_classification/api/model.py
  src/rubrix/server/tasks/text_classification/service/service.py
  tests/labeling/text_classification/test_rule.py
Labels: bug

#848 fix(rules): prevent division by 0 for overall metrics
  src/rubrix/server/tasks/text_classification/api/model.py
  src/rubrix/server/tasks/text_classification/service/service.py
  tests/server/text_classification/test_api_rules.py
Labels: bug, server

#851 [Tutorials] Add streaming to the spacy tutorial
  docs/tutorials/02-spacy.ipynb
Labels: documentation

#850 fix(metrics): compute token length for each token
  src/rubrix/server/tasks/token_classification/metrics.py
  tests/functional_tests/test_log_for_token_classification.py
Labels: bug

#845 fix: error link to workspace home
  frontend/components/commons/Error.vue
  frontend/pages/ws/_workspace/_dataset/index.vue
  frontend/pages/ws/_workspace/index.vue
Labels: bug, app
