Repository argilla-io/argilla, pull requests merged in 2022-08, with the labels that each got.

#1640 perf: reusing the inner `httpx` client
  src/rubrix/client/api.py
  src/rubrix/client/sdk/client.py
  src/rubrix/client/sdk/text2text/api.py
  src/rubrix/client/sdk/text_classification/api.py
  src/rubrix/client/sdk/token_classification/api.py
  src/rubrix/client/sdk/users/api.py
  src/rubrix/utils.py
  tests/client/sdk/conftest.py
  tests/client/sdk/text2text/test_api.py
  tests/client/sdk/text_classification/test_api.py
  tests/client/sdk/token_classification/test_api.py
  tests/client/sdk/users/test_api.py
  tests/client/test_api.py
  tests/client/test_init.py
  tests/conftest.py
  tests/helpers.py
Labels: client

#1659 Feat/search after
  src/rubrix/client/api.py
  src/rubrix/client/sdk/commons/api.py
  src/rubrix/client/sdk/text2text/api.py
  src/rubrix/client/sdk/text_classification/api.py
  src/rubrix/client/sdk/token_classification/api.py
  src/rubrix/server/apis/v0/handlers/text2text.py
  src/rubrix/server/apis/v0/handlers/text_classification.py
  src/rubrix/server/apis/v0/handlers/token_classification.py
  src/rubrix/server/daos/models/records.py
  src/rubrix/server/daos/records.py
  src/rubrix/server/elasticseach/client_wrapper.py
  src/rubrix/server/services/search/service.py
  src/rubrix/server/services/text2text.py
  src/rubrix/server/services/text_classification.py
  src/rubrix/server/services/token_classification.py
Labels: enhancement

#1688 Add Slack support link in README's get started
  README.md
  docs/index.md
Labels: documentation

#1625 feat: Copy Record Text
  frontend/assets/scss/base/base.scss
  frontend/components/commons/results/RecordExtraActions.vue
  frontend/components/core/ReBreadcrumbs.vue
  frontend/components/core/ReCode.vue
  frontend/models/Text2Text.js
  frontend/models/TextClassification.js
  frontend/models/TokenClassification.js
  frontend/nuxt.config.js
  frontend/pages/datasets/index.vue
  frontend/plugins/copy-to-clipboard.js
  frontend/specs/components/commons/results/RecordExtraAtions.spec.js
  frontend/specs/components/commons/results/__snapshots__/RecordExtraAtions.spec.js.snap
Labels: enhancement, ui
