Repository argilla-io/argilla, pull requests merged in 2022-01, with the labels that each got.

#892 fix(rules): prevent lost rules with dataset updates
  src/rubrix/server/commons/es_wrapper.py
  src/rubrix/server/datasets/dao.py
  tests/server/text_classification/test_api_rules.py
Labels: bug

#925 [WeakLabels] Align WeakLabels.summary() with web app
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: labeling

#922 [Tutorials] Update skweak tutorial
  docs/tutorials/skweak.ipynb
Labels: documentation

#930 [WeakLabels] Show nan instead of 0 for precision in summary
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: labeling

#934 Bugfixes/avoid infinite loop when dataset loading
  frontend/components/text-classifier/labeling-rules/RulesManagement.vue
  frontend/database/modules/datasets.js
Labels: bug, app

#936 [WebAppReference] Fix links to new web app reference documentation
  README.md
  docs/guides/weak-supervision.ipynb
  docs/tutorials/07-zeroshot_ner.ipynb
  src/rubrix/__init__.py
  src/rubrix/client/rubrix_client.py
  src/rubrix/labeling/text_classification/rule.py
  src/rubrix/labeling/text_classification/weak_labels.py
  src/rubrix/metrics/commons.py
  src/rubrix/metrics/text_classification/metrics.py
  src/rubrix/metrics/token_classification/metrics.py
Labels: documentation

#939 [WeakSupervision] Change load_rules import path in guide and tutorial
  docs/guides/weak-supervision.ipynb
  docs/tutorials/weak-supervision-with-rubrix.ipynb
Labels: documentation, labeling

#941 [Weak Supervision Guide] Fix links
  docs/guides/weak-supervision.ipynb
  docs/reference/webapp/search_records.md
Labels: documentation

#943 docs(#935): Update weak supervision guide with new weasel integrations
  docs/guides/weak-supervision.ipynb
Labels: documentation

#976 feat(#955): add default for `rules` in WeakLabels
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: labeling

#878 refactor(rules): using labeling rules management with vuex store
  frontend/components/core/ReModal.vue
  frontend/components/text-classifier/labeling-rules/RuleDefinition.vue
  frontend/components/text-classifier/labeling-rules/RuleLabelsDefinition.vue
  frontend/components/text-classifier/labeling-rules/RulesManagement.vue
  frontend/components/text-classifier/labeling-rules/RulesMetrics.vue
  frontend/components/text-classifier/results/RecordTextClassification.vue
  frontend/database/modules/datasets.js
  frontend/database/modules/text_classification.js
  frontend/models/TextClassification.js
Labels: enhancement, app

#979 feat(#953): add additional metrics to `LabelModel.score` method
  src/rubrix/labeling/text_classification/label_models.py
  tests/labeling/text_classification/test_label_models.py
Labels: labeling

#985 docs: improve annotate records section in web app reference
  docs/_static/reference/webapp/bulk_annotate.png
  docs/_static/reference/webapp/create_newlabel.png
  docs/_static/reference/webapp/progress_bar.png
  docs/_static/reference/webapp/text2text_annotation.png
  docs/_static/reference/webapp/textclassification_multilabel.png
  docs/reference/webapp/annotate_records.md
Labels: documentation

#1005 refactor: Rename 'exclude_missing_annotation' argument for WeakLabels.annotation
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: labeling

#1006 fix(statics): handle 404 errors for static files
  src/rubrix/server/commons/static_rewrite.py
Labels: bug, app

#1003 fix(Breadcrumbs): copy workspace from the breadcrumbs when dataset loading has errors
  frontend/components/core/ReBreadcrumbs.vue
Labels: bug, app

#1011 fix(#1010): fix WeakLabels when not providing rules
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: bug, labeling

#1016 fix(#1015): manage emojis in Token Classification records
  frontend/components/token-classifier/results/TextSpan.vue
  frontend/models/TokenClassification.js
  frontend/package.json
Labels: bug, app

#1004 docs(#980): Add majorityvote example to weak supervision guide
  docs/guides/weak-supervision.ipynb
Labels: documentation

#1024 fix(#1008): set the event_timestamp when annotating TextClassifier
  frontend/models/Common.js
Labels: bug

#1022 feat(#945): change es analyzers using environment variables
  docs/getting_started/advanced_setup_guides.rst
  src/rubrix/server/commons/settings.py
  src/rubrix/server/tasks/commons/dao/es_config.py
Labels: enhancement

#1032 Fix(#1027): Improve client models by reordering fields + forbidding extra args
  src/rubrix/client/models.py
  tests/client/test_models.py
Labels: bug

#1037 feat(#1036): remove prediction ok/ko in labelling rules
  frontend/components/text-classifier/results/RecordTextClassification.vue
Labels: app

#1040 docs(#994): Change setup guide to recommend using python to start the server
  README.md
  docs/getting_started/advanced_setup_guides.rst
  docs/getting_started/setup&installation.rst
  docs/index.rst
Labels: documentation

#1031 refactor(#924): normalize API error responses
  src/rubrix/errors.py
  src/rubrix/server/commons/errors.py
  src/rubrix/server/commons/errors/__init__.py
  src/rubrix/server/commons/errors/adapter.py
  src/rubrix/server/commons/errors/api_errors.py
  src/rubrix/server/commons/errors/base_errors.py
  src/rubrix/server/commons/es_helpers.py
  src/rubrix/server/commons/settings.py
  src/rubrix/server/routes.py
  src/rubrix/server/server.py
  src/rubrix/server/tasks/commons/api/errors.py
  src/rubrix/server/tasks/commons/api/model.py
  src/rubrix/server/tasks/commons/dao/dao.py
  tests/client/test_asgi.py
  tests/client/test_rubrix_client.py
  tests/functional_tests/test_log_for_text_classification.py
  tests/labeling/text_classification/test_rule.py
  tests/server/datasets/test_api.py
  tests/server/metrics/test_api.py
  tests/server/test_helpers.py
  tests/server/text_classification/test_api.py
  tests/server/text_classification/test_api_rules.py
  tests/server/token_classification/test_api.py
Labels: server

#1049 feat(#932): label models now modify the prediction_agent when calling LabelModel.predict
  src/rubrix/labeling/text_classification/label_models.py
  tests/labeling/text_classification/test_label_models.py
Labels: labeling

#1055 fix(#1050): generalizes entity span validation
  src/rubrix/server/tasks/token_classification/api/model.py
  src/rubrix/server/tasks/token_classification/metrics.py
  tests/server/token_classification/test_model.py
Labels: bug, server

#1066 fix(#1065): 'B' tag for beginning tokens
  src/rubrix/server/tasks/token_classification/metrics.py
  tests/functional_tests/test_log_for_token_classification.py
Labels: bug
