Repository argilla-io/argilla, pull requests merged in 2022-06, with the labels that each got.

#1530 fix(metrics): compute f1 for text classification
  src/rubrix/metrics/helpers.py
  src/rubrix/server/apis/v0/models/metrics/text_classification.py
  tests/metrics/test_text_classification.py
Labels: bug

#1477 docs(#1456): Introduce a tutorials gallery
  docs/_static/css/custom.css
  docs/_static/guides/weak_supervision/weak_supervision.svg
  docs/_static/tutorials/01-labeling-finetuning/label.png
  docs/_static/tutorials/01-labeling-finetuning/tutorial_thumbnail.png
  docs/_static/tutorials/07-zeroshot_ner/gallery_thumbnail.png
  docs/_static/tutorials/08-error_analysis_using_loss/gallery_thumbnail.png
  docs/_static/tutorials/09-automatic_fastapi/gallery_thumbnail.png
  docs/_static/tutorials/extend_weak_labels_with_embeddings/extend_weak_labels.png
  docs/_static/tutorials/weak-supervision-multi-label/gallery_thumbnail.png
  docs/_static/tutorials/weak-supervision-with-rubrix/news_tutorial.gif
  docs/_static/tutorials/weak-supervision-with-rubrix/weak_supervision1.svg
  docs/conf.py
  docs/guides/weak-supervision.ipynb
  docs/index.rst
  docs/reference/webapp/filter_records.md
  docs/tutorials/01-labeling-finetuning.ipynb
  docs/tutorials/02-spacy.ipynb
  docs/tutorials/05-active_learning.ipynb
  docs/tutorials/07-zeroshot_ner.ipynb
  docs/tutorials/08-error_analysis_using_loss.ipynb
  docs/tutorials/09-automatic_fastapi_log.ipynb
  docs/tutorials/active-learning.md
  docs/tutorials/extend_weak_labels_with_embeddings.ipynb
  docs/tutorials/find_label_errors.ipynb
  docs/tutorials/introductory.md
  docs/tutorials/label-errors.md
  docs/tutorials/model_predictions.md
  docs/tutorials/monitoring.md
  docs/tutorials/skweak.ipynb
  docs/tutorials/weak-supervision-multi-label.ipynb
  docs/tutorials/weak-supervision-with-rubrix.ipynb
  docs/tutorials/weak-supervision.md
  environment_dev.yml
  environment_docs.yml
Labels: documentation

#1537 docs: introduce basics
  docs/_static/getting_started/basics/coffee_reviews.png
  docs/_static/getting_started/basics/ecdc_phrases.png
  docs/_static/getting_started/basics/first_record.png
  docs/_static/getting_started/basics/manual_annotations.png
  docs/_static/getting_started/basics/snapchat_reviews.png
  docs/getting_started/basics.ipynb
  docs/index.rst
  docs/reference/webapp/annotate_records.md
Labels: documentation

#1549 docs: Review index and basics
  README.md
  docs/getting_started/basics.ipynb
  docs/index.rst
Labels: documentation

#1552 docs(#1546): Add docker command to setup
  docs/getting_started/setup&installation.rst
Labels: documentation

#1558 fix(#1557): Allow text editing when clicking the "edit" button
  frontend/components/text2text/results/RecordText2Text.vue
Labels: bug

#1566 fix: compatibility with new dataset version
  environment_dev.yml
  src/rubrix/client/datasets.py
Labels: bug, client

#1560 docs: Add pip version and dockertag as parameter in the build process
  docs/conf.py
  docs/getting_started/advanced_setup_guides.md
  docs/getting_started/advanced_setup_guides.rst
  docs/getting_started/setup&installation.md
  docs/getting_started/setup&installation.rst
  docs/getting_started/user-management.ipynb
  docs/getting_started/user-management.md
  docs/index.md
  docs/reference/webapp/index.md
Labels: documentation

#1577 feat: Add 'extend_matrix' to the WeakMultiLabel class
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: labeling

#1582 docs: Add MajorityVoter to references + Add comments about multi-label support of the label models
  docs/guides/weak-supervision.ipynb
  docs/reference/python/python_labeling.rst
  docs/tutorials/weak-supervision-multi-label.ipynb
  src/rubrix/labeling/text_classification/label_models.py
Labels: documentation

#1586 refactor(listener): support dynamic query parameters
  src/rubrix/listeners/listener.py
  src/rubrix/listeners/models.py
  tests/listeners/test_listener.py
Labels: client

#1593 test: configure numpy to disable multi threading
  tests/__init__.py
Labels: tests

#1595 refactor(server): apis > services > daos relations
  src/rubrix/server/apis/v0/models/datasets.py
  src/rubrix/server/daos/datasets.py
  src/rubrix/server/daos/models/datasets.py
  src/rubrix/server/daos/records.py
  src/rubrix/server/services/datasets.py
Labels: technical debt

#1594 refactor(server): moving shared module settings to common server folder
  src/rubrix/server/apis/v0/settings/__init__.py
  src/rubrix/server/daos/records.py
  src/rubrix/server/elasticseach/client_wrapper.py
  src/rubrix/server/elasticseach/mappings/datasets.py
  src/rubrix/server/elasticseach/mappings/helpers.py
  src/rubrix/server/server.py
  src/rubrix/server/settings.py
  tests/functional_tests/test_log_for_text_classification.py
  tests/server/commons/test_settings.py
Labels: technical debt
