Repository argilla-io/argilla, pull requests merged in 2022-11, with the labels that each got.

#1896 Docs/fix read the docs build
  .readthedocs.yaml
  environment_docs.yml
Labels: bug, documentation

#1884 feat: Add, delete and edit rules from Python client
  docs/_source/_static/datasets/weak_supervision_tutorial/labeling_rules.csv
  docs/_source/guides/techniques/weak_supervision.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-sentencetransformers-weaksupervision.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-sklearn-weaksupervision.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-snorkel-weaksupervision.ipynb
  src/argilla/client/api.py
  src/argilla/client/sdk/text_classification/api.py
  src/argilla/client/sdk/text_classification/models.py
  src/argilla/labeling/text_classification/__init__.py
  src/argilla/labeling/text_classification/rule.py
  tests/client/sdk/conftest.py
  tests/client/sdk/text_classification/test_models.py
  tests/conftest.py
  tests/labeling/text_classification/test_rule.py
Labels: enhancement, Labeling

#1950 Docs/1.1.0 release update helper button and record card access
  docs/_source/reference/webapp/features.md
  docs/_source/reference/webapp/pages.md
  docs/_source/tutorials/libraries/sentencetransformers.md
Labels: documentation

#1956 #1945 added autodoc references to monitoring methods
  docs/_source/reference/python/index.rst
  docs/_source/reference/python/python_monitoring.rst
Labels: documentation

#1970 feat: Feature/set record timestamp by defeault
  src/argilla/client/models.py
  tests/client/test_models.py
Labels: enhancement

#1960 Feat/improve telemetry settings and documentation docker compose
  docker-compose.yaml
  docs/_source/getting_started/installation/docker.md
  docs/_source/getting_started/installation/docker_compose.md
  docs/_source/getting_started/installation/installation.md
  docs/_source/getting_started/installation/server_configuration.md
  docs/_source/getting_started/quickstart.ipynb
Labels: documentation

#1980 feat: #1979 revert changes renaming text2text to textgeneration
  docs/_source/_common/tasks_all.md
  docs/_source/_common/tasks_points.md
  docs/_source/_static/reference/webapp/explore-text2text.png
  docs/_source/getting_started/quickstart.ipynb
  docs/_source/getting_started/terminology.md
  docs/_source/guides/features/datasets.ipynb
  docs/_source/guides/steps/3_deploying.ipynb
  docs/_source/guides/tasks/text_generation.ipynb
  docs/_source/reference/datamodel.md
  docs/_source/reference/python/python_client.rst
  docs/_source/reference/webapp/features.md
  docs/_source/reference/webapp/pages.md
  src/argilla/__init__.py
  src/argilla/client/api.py
  src/argilla/client/models.py
Labels: enhancement
