Repository argilla-io/argilla, pull requests merged in 2022-04, with the labels that each got.

#1371 fix: Computation of capitalness (metrics) when value.strip() results in empty str
  src/rubrix/server/tasks/token_classification/metrics.py
  tests/metrics/test_token_classification.py
Labels: bug

#1380 fix(search): compute dataset schema properly
  environment_dev.yml
  src/rubrix/server/tasks/commons/dao/dao.py
  tests/functional_tests/search/test_search_service.py
Labels: bug, server

#1385 fix(#1367): remove record text from metadata modal
  frontend/components/commons/results/Metadata.vue
Labels: bug, ui

#1386 fix(#1382): update image path
  docs/conf.py
Labels: bug, documentation

#1396 fix(metrics): increment default aggregation size
  src/rubrix/server/commons/es_helpers.py
Labels: bug

#1392 docs: fix metric definitions in the Define Rules references
  docs/reference/webapp/define_rules.md
Labels: bug, documentation

#1401 fix(search): prevent exceed search.max buckets for metadata fields
  src/rubrix/server/commons/es_helpers.py
  src/rubrix/server/tasks/commons/metrics/model/base.py
  src/rubrix/server/tasks/commons/metrics/service.py
Labels: bug

#1388 fix(#1368): long list of entities in Token Classifier
  frontend/components/token-classifier/results/EntitiesHeader.vue
  frontend/components/token-classifier/results/EntitiesSelector.vue
  frontend/components/token-classifier/results/RecordTokenClassification.vue
  frontend/components/token-classifier/results/TextSpan.vue
  frontend/components/token-classifier/results/TextSpanStatic.vue
  frontend/components/token-classifier/sidebar/TokenClassificationProgress.vue
  frontend/components/token-classifier/sidebar/TokenClassificationStats.vue
  frontend/nuxt.config.js
  frontend/plugins/variables.js
  frontend/specs/components/token-classification/results/EntitiesSelector.spec.js
Labels: bug, ui

#1406 [UI] Force break word in selectors
  frontend/components/commons/header/filters/SortFilter.vue
  frontend/components/core/ReCheckbox.vue
  frontend/components/text-classifier/header/global-actions/AnnotationLabelSelector.vue
  frontend/components/token-classifier/results/EntitiesSelector.vue
Labels: bug

#1422 test: initializing test client with startup event handling
  tests/conftest.py
Labels: enhancement, tests

#1423 refactor: allow launch server without statics folder
  src/rubrix/server/server.py
Labels: server

#1426 fix(datasets): using provided task for list datasets
  src/rubrix/server/datasets/service.py
Labels: fix

#1436 fix(#1428): support cleanlab v2
  .github/workflows/ci.yml
  environment_dev.yml
  src/rubrix/labeling/text_classification/label_errors.py
  tests/labeling/text_classification/test_label_errors.py
Labels: labeling

#1438 refactor: use entity score as default record score
  src/rubrix/server/apis/v0/models/token_classification.py
  tests/server/token_classification/test_model.py
Labels: server

#1443 docs: update og image of the readme
  docs/images/og_rubrix.png
Labels: documentation

#1434 docs(#1430): Remove experimental and update query url link
  docs/guides/task_examples.ipynb
  docs/reference/python/python_labeling.rst
  docs/reference/python/python_metrics.rst
  src/rubrix/client/api.py
  src/rubrix/client/rubrix_client.py
  src/rubrix/labeling/text_classification/rule.py
  src/rubrix/labeling/text_classification/weak_labels.py
  src/rubrix/metrics/commons.py
  src/rubrix/metrics/text_classification/metrics.py
  src/rubrix/metrics/token_classification/metrics.py
Labels: documentation

#1442 feat(#1247): label models predict method returns DatasetForTextClassification
  docs/tutorials/weak-supervision-multi-label.ipynb
  docs/tutorials/weak-supervision-with-rubrix.ipynb
  src/rubrix/labeling/text_classification/label_models.py
Labels: documentation, labeling
