Repository argilla-io/argilla, pull requests merged in 2022-03, with the labels that each got.

#1209 feat: Implement 'prepare_for_training' for text classification datasets
  docs/tutorials/01-labeling-finetuning.ipynb
  src/rubrix/client/datasets.py
  tests/client/test_dataset.py
Labels: client

#1205 docs(#1092): update skweak tutorial to show new NER feature
  docs/_static/tutorials/skweak/skweak.mp4
  docs/_static/tutorials/skweak/skweak_1.gif
  docs/_static/tutorials/skweak/skweak_1.png
  docs/_static/tutorials/skweak/skweak_2.png
  docs/_static/tutorials/skweak/skweak_3.png
  docs/_static/tutorials/skweak/skweak_4.png
  docs/_static/tutorials/skweak/skweak_5.png
  docs/_static/tutorials/skweak/skweak_6.png
  docs/getting_started/advanced_setup_guides.rst
  docs/getting_started/setup&installation.rst
  docs/reference/webapp/annotate_records.md
  docs/tutorials/skweak.ipynb
Labels: documentation

#1222 docs(setup): the current section format is a bit weird
  docs/getting_started/advanced_setup_guides.rst
Labels: documentation

#1224 chore(#1029): generalize logging configuration message
  src/rubrix/logging.py
Labels: documentation

#1227 docs: switch out zero shot example video with updated screenshot
  README.md
  docs/images/zero_shot_example.png
  docs/index.rst
Labels: documentation

#1226 feat(#1225): create iob tags from record spans
  src/rubrix/client/datasets.py
  src/rubrix/client/models.py
  tests/client/test_asgi.py
  tests/client/test_models.py
  tests/functional_tests/test_log_for_token_classification.py
Labels: client

#1230 refactor(#945): unify query to elasticsearch generation
  src/rubrix/server/commons/es_helpers.py
  src/rubrix/server/tasks/commons/api/model.py
  src/rubrix/server/tasks/commons/metrics/commons.py
  src/rubrix/server/tasks/search/model.py
  src/rubrix/server/tasks/search/query_builder.py
  src/rubrix/server/tasks/text2text/api/model.py
  src/rubrix/server/tasks/text_classification/api/model.py
  src/rubrix/server/tasks/text_classification/service/labeling_service.py
  src/rubrix/server/tasks/token_classification/api/model.py
  tests/server/text2text/test_model.py
  tests/server/text_classification/test_model.py
  tests/server/token_classification/test_model.py
Labels: server

#1237 fix: computation of correct/incorrect in weak multi label summary
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: bug, labeling

#1250 docs: adds readme banner
  README.md
Labels: documentation

#1251 docs(#1242, #1240, #1221): Add env var section + other minor fixes
  docs/getting_started/advanced_setup_guides.rst
  docs/getting_started/setup&installation.rst
  docs/getting_started/supported_tasks.rst
  docs/guides/weak-supervision.ipynb
  docs/index.rst
  environment_dev.yml
  environment_docs.yml
  src/rubrix/client/api.py
Labels: documentation

#1246 feat: Introduce a 'text' argument for the TextClassificationRecord
  README.md
  docs/getting_started/concepts.rst
  docs/getting_started/setup&installation.rst
  docs/guides/cookbook.ipynb
  docs/guides/datasets.ipynb
  docs/guides/metrics.ipynb
  docs/guides/task_examples.ipynb
  docs/guides/weak-supervision.ipynb
  docs/index.rst
  docs/tutorials/01-labeling-finetuning.ipynb
  docs/tutorials/05-active_learning.ipynb
  docs/tutorials/08-error_analysis_using_loss.ipynb
  docs/tutorials/find_label_errors.ipynb
  docs/tutorials/weak-supervision-with-rubrix.ipynb
  src/rubrix/client/api.py
  src/rubrix/client/datasets.py
  src/rubrix/client/models.py
  src/rubrix/labeling/text_classification/weak_labels.py
  src/rubrix/monitoring/_transformers.py
  tests/client/sdk/text_classification/test_api.py
  tests/client/sdk/text_classification/test_models.py
  tests/client/test_dataset.py
  tests/client/test_models.py
  tests/functional_tests/test_log_for_text_classification.py
  tests/labeling/text_classification/test_label_errors.py
  tests/labeling/text_classification/test_label_models.py
  tests/labeling/text_classification/test_rule.py
  tests/labeling/text_classification/test_weak_labels.py
  tests/metrics/test_text_classification.py
Labels: client

#1269 docs(#1267): move docker command to one line
  README.md
  docs/getting_started/advanced_setup_guides.rst
  docs/getting_started/supported_tasks.rst
  docs/guides/task_examples.ipynb
  docs/index.rst
Labels: documentation

#1283 fix(NER): create record annotation from tags (also in DatasetForTokenClassification.from_datasets)
  src/rubrix/client/datasets.py
  src/rubrix/client/models.py
  tests/client/test_models.py
Labels: bug

#1284 fix(datasets): prevent error when no annotated records found in dataset
  src/rubrix/client/datasets.py
  tests/client/test_dataset.py
Labels: bug

#1268 fix(#984): manage super user workspaces
  frontend/components/commons/header/user/user.vue
  frontend/database/modules/datasets.js
  frontend/models/Workspace.js
  frontend/plugins/vuex-orm-axios.js
  src/rubrix/client/api.py
  src/rubrix/server/commons/api.py
  src/rubrix/server/commons/errors/base_errors.py
  src/rubrix/server/commons/es_wrapper.py
  src/rubrix/server/datasets/api.py
  src/rubrix/server/datasets/dao.py
  src/rubrix/server/datasets/service.py
  src/rubrix/server/security/auth_provider/local/provider.py
  src/rubrix/server/security/auth_provider/local/users/dao.py
  src/rubrix/server/security/auth_provider/local/users/service.py
  src/rubrix/server/security/model.py
  src/rubrix/server/tasks/text_classification/api/api_labeling.py
  src/rubrix/server/tasks/text_classification/service/model.py
  tests/client/test_api.py
  tests/client/test_rubrix_client.py
  tests/functional_tests/search/__init__.py
  tests/functional_tests/search/test_search_service.py
  tests/helpers.py
  tests/server/datasets/test_api.py
  tests/server/security/test_model.py
  tests/server/security/test_service.py
Labels: bug

#1288 fix(workspaces): superuser with empty workspace
  src/rubrix/server/security/model.py
  tests/server/security/test_model.py
Labels: bug

#1285 refactor(labels): compute dataset labels from a records subset
  src/rubrix/server/tasks/text_classification/metrics.py
Labels: enhancement, server

#1290 refactor(workspaces): find datasets without workspace for superusers
  src/rubrix/server/datasets/model.py
  src/rubrix/server/datasets/service.py
  src/rubrix/server/security/model.py
  tests/client/test_api.py
Labels: server

#1295 fix: make starlette an optional dependency
  setup.cfg
  src/rubrix/monitoring/asgi.py
Labels: client

#1301 docs: move search ref to guides
  docs/guides/queries.md
  docs/index.rst
  docs/reference/webapp/search_records.md
Labels: documentation

#1304 fix(#1286): backward comp. sorting by id
  release.Dockerfile
  src/rubrix/server/commons/es_wrapper.py
  src/rubrix/server/tasks/commons/dao/dao.py
Labels: bug

#1277 docs(1272): Add instructions on how to import "generic" datasets to Rubrix
  docs/guides/datasets.ipynb
  src/rubrix/client/datasets.py
  tests/client/test_dataset.py
Labels: documentation

#1354 docs: single-quoted queries
  docs/tutorials/weak-supervision-multi-label.ipynb
Labels: documentation

#1345 docs: update define rules reference + add video to ws multi-label tutorial
  docs/_static/reference/webapp/definerules_view.png
  docs/_static/reference/webapp/label1.png
  docs/_static/reference/webapp/label5.png
  docs/_static/reference/webapp/label_rulemetrics.png
  docs/_static/tutorials/weak-supervision-multi-label/ws_multi-label.mp4
  docs/reference/webapp/define_rules.md
  docs/tutorials/weak-supervision-multi-label.ipynb
  frontend/components/text-classifier/labeling-rules/RulesManagement.vue
  frontend/components/text-classifier/labeling-rules/RulesMetrics.vue
  src/rubrix/labeling/text_classification/weak_labels.py
Labels: documentation, labeling, ui

#1348 docs(#428): Add example to cookbook about fine-tuning a transformer for token class
  docs/guides/cookbook.ipynb
Labels: documentation

#1357 chore(#1310): space between records to 1px
  frontend/components/commons/results/ResultsList.vue
  frontend/components/commons/results/ResultsRecord.vue
Labels: ui

#1366 docs: fix weak supervision single-label tutorial
  docs/_static/tutorials/find_label_errors/tldr_poster.png
  docs/tutorials/find_label_errors.ipynb
  docs/tutorials/weak-supervision-with-rubrix.ipynb
Labels: bug, documentation
