Repository argilla-io/argilla, pull requests merged in 2022-07, with the labels that each got.

#1598 refactor(server): moving common base models to services layer
  src/rubrix/server/apis/v0/models/commons/model.py
  src/rubrix/server/services/datasets.py
  src/rubrix/server/services/metrics.py
  src/rubrix/server/services/search/model.py
  src/rubrix/server/services/search/query_builder.py
  src/rubrix/server/services/search/service.py
  src/rubrix/server/services/tasks/__init__.py
  src/rubrix/server/services/tasks/commons/__init__.py
  src/rubrix/server/services/tasks/commons/logging.py
  src/rubrix/server/services/tasks/commons/record.py
Labels: technical debt

#1589 docs: add 'how to prepare your data for training' to basics
  docs/getting_started/basics.ipynb
Labels: documentation

#1609 docs(#): implement christopher comments
  docs/tutorials/active_learning_with_small_text.ipynb
Labels: documentation

#1612 docs: Add listeners dep to tutorial
  docs/tutorials/active_learning_with_small_text.ipynb
Labels: bug, documentation

#1613 docs: fix typo in active learning tutorial with small-text
  docs/tutorials/active_learning_with_small_text.ipynb
Labels: documentation

#1620 fix: Show predicted OK/KO when predictions exist
  frontend/models/TextClassification.js
  frontend/specs/components/text-classification/results/RecordTextClassification.spec.js
  frontend/specs/components/text-classification/results/__snapshots__/RecordTextClassification.spec.js.snap
Labels: bug

#1618 docs: Fix typo in Getting Started -> Concepts
  docs/getting_started/concepts.md
Labels: bug, documentation

#1633 fix: 'WeakMultiLabels.summary' and 'show_records' after extending the weak label matrix
  src/rubrix/labeling/text_classification/weak_labels.py
  tests/labeling/text_classification/test_weak_labels.py
Labels: bug, labeling

#1639 chore: remove old rubrix client class
  src/rubrix/client/__init__.py
  src/rubrix/client/rubrix_client.py
  tests/client/test_rubrix_client.py
Labels: client

#1643 Documentation improvements
  docs/getting_started/advanced_setup_guides.md
Labels: documentation

#1648 feat(Error Logging): send error detail in response for generic server errors
  src/rubrix/server/errors/base_errors.py
  tests/server/test_errors.py
Labels: enhancement
