Repository argilla-io/argilla, pull requests merged in 2023-09, with the labels that each got.

#3694 build: skip CI trigger when PR is draft
  .github/workflows/dependency-review.yml
  .github/workflows/package.yml
Labels: ci

#3676 feat/cli : add `python -m argilla workspaces create` command
  CHANGELOG.md
  src/argilla/tasks/workspaces/__main__.py
  src/argilla/tasks/workspaces/create.py
  tests/unit/tasks/workspaces/test_create.py
Labels: cli

#3677 🛣️ Feat/improve queue annotation
  CHANGELOG.md
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/models/feedback-task-model/record/record.queries.js
  frontend/v1/domain/entities/record/Record.ts
  frontend/v1/domain/entities/record/Records.ts
  frontend/v1/domain/services/IDatasetSettingStorage.ts
  frontend/v1/domain/usecases/get-records-to-annotate-use-case.ts
  frontend/v1/infrastructure/repositories/RecordRepository.ts
  frontend/v1/infrastructure/storage/RecordsStorage.ts
  frontend/v1/store/create.ts
Labels: ui

#3699 feat: add `workspace delete-user` command
  CHANGELOG.md
  src/argilla/client/users.py
  src/argilla/tasks/workspaces/__main__.py
  src/argilla/tasks/workspaces/delete_user.py
  tests/integration/client/test_users.py
  tests/unit/tasks/conftest.py
  tests/unit/tasks/users/conftest.py
  tests/unit/tasks/workspaces/test_delete_user.py
Labels: enhancement, cli

#3709 feat: add `updated_at` and `created_at` attributes for `FeedbackDataset` in Argilla
  CHANGELOG.md
  src/argilla/client/feedback/dataset/mixins.py
  src/argilla/client/feedback/dataset/remote/base.py
  src/argilla/client/feedback/dataset/remote/dataset.py
  src/argilla/client/feedback/dataset/remote/filtered.py
  src/argilla/tasks/datasets/list.py
  tests/integration/client/feedback/dataset/remote/test_dataset.py
  tests/integration/client/feedback/dataset/remote/test_filtered.py
  tests/unit/tasks/datasets/conftest.py
  tests/unit/tasks/datasets/test_list.py
Labels: client

#3711 feat: update `update_response` endpoint to replace `values`
  CHANGELOG.md
  src/argilla/server/contexts/datasets.py
  src/argilla/server/models/mixins.py
  src/argilla/server/models/questions.py
  tests/unit/server/api/v1/test_responses.py
  tests/unit/server/models/test_base.py
Labels: enhancement, api

#3713 fix: `users create` command was not printing workspace names
  src/argilla/tasks/users/create.py
  tests/unit/tasks/users/test_create.py
Labels: bug 🪲, cli

#3702 fix: default behaviour for `visible_labels` in `LabelQuestion` and `MultiLabelQuestion`
  CHANGELOG.md
  src/argilla/client/feedback/schemas/questions.py
  tests/unit/client/feedback/schemas/test_questions.py
Labels: client, bugfix

#3716 fix: display `UserWarning` in `add_user` and `delete_user` when ID is from an `owner`
  CHANGELOG.md
  src/argilla/client/workspaces.py
  tests/integration/client/test_workspaces.py
Labels: enhancement, client

#3712 feat: add `workspace add-user` command
  CHANGELOG.md
  src/argilla/tasks/workspaces/__main__.py
  src/argilla/tasks/workspaces/add_user.py
  tests/unit/tasks/workspaces/test_add_user.py
Labels: enhancement, cli

#3718 fix: exclude `id` and `client` from `suggestions` in `DatasetCard`
  CHANGELOG.md
  src/argilla/client/feedback/integrations/huggingface/dataset.py
Labels: client, bugfix

#3725 :rotating_light: fix console warning due to missing props
  frontend/components/features/datasets/datasets-settings/LeftDatasetSettings.content.vue
Labels: bug 🪲, ui

#3729 refactor: reuse `UserModel` and remove duplicated `WorkspaceUserModel`
  src/argilla/client/sdk/users/models.py
  src/argilla/client/sdk/workspaces/api.py
  src/argilla/client/sdk/workspaces/models.py
  src/argilla/client/workspaces.py
  tests/integration/client/sdk/api/test_workspaces.py
  tests/integration/client/test_workspaces.py
Labels: refactor

#3727 feat: add `workspace_id` param to `GET /api/v1/me/datasets`
  CHANGELOG.md
  src/argilla/client/feedback/dataset/mixins.py
  src/argilla/client/sdk/v1/datasets/api.py
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/policies.py
  tests/integration/client/sdk/v1/test_datasets.py
  tests/unit/server/api/v1/test_datasets.py
Labels: enhancement, client

#3730 feat: add `argilla` script
  CHANGELOG.md
  pyproject.toml
Labels: enhancement, cli

#3734 ✨ Fix title width
  CHANGELOG.md
  frontend/components/feedback-task/field/TextField.component.vue
Labels: bugfix

#3736 fix: `SearchEngine` had num index == num replicas
  CHANGELOG.md
  src/argilla/server/search_engine.py
Labels: api, bugfix

#3744 feat: add `Vector` and `VectorSettings` ORM classes
  src/argilla/server/alembic/versions/66e63faf4a33_create_vectors_table.py
  src/argilla/server/alembic/versions/7850ab5b42d9_create_vectors_settings_table.py
  src/argilla/server/models/models.py
Labels: enhancement, api

#3752 feat: add `username` option to `users` group of commands
  src/argilla/cli/users/__main__.py
  src/argilla/cli/users/create.py
  src/argilla/cli/users/delete.py
  tests/unit/cli/users/test_delete.py
Labels: enhancement, cli

#3753 feat: update group of commands help
  src/argilla/cli/datasets/__main__.py
  src/argilla/cli/logout/__main__.py
  src/argilla/cli/server/__main__.py
  src/argilla/cli/server/database/__main__.py
  src/argilla/cli/server/database/users/__main__.py
  src/argilla/cli/training/__main__.py
  src/argilla/cli/users/__main__.py
  src/argilla/cli/workspaces/__main__.py
Labels: enhancement, cli

#3754 fix: ensure `argilla database` backwards compatibility
  CHANGELOG.md
  src/argilla/cli/app.py
  src/argilla/cli/callback.py
Labels: backwards compatibility

#3758 docs: add `CLI` reference section and update pages w/ commands
  docs/_source/_common/tabs/argilla_connect.md
  docs/_source/community/developer_docs.md
  docs/_source/community/migration-rubrix.md
  docs/_source/getting_started/installation/configurations/configurations.md
  docs/_source/getting_started/installation/configurations/database_migrations.md
  docs/_source/getting_started/installation/configurations/user_management.md
  docs/_source/getting_started/installation/configurations/workspace_management.md
  docs/_source/guides/label_records_with_semanticsearch.ipynb
  docs/_source/guides/train_a_model.md
  docs/_source/index.rst
  docs/_source/reference/cli.md
  docs/_source/tutorials/notebooks/deploying-textclassification-colab-activelearning.ipynb
  docs/migration-rubrix.md
  src/argilla/client/api.py
  src/argilla/client/client.py
Labels: documentation, cli

#3555 feat: allow `require_version` and `requires_version` to also accept list of requirements
  src/argilla/client/datasets.py
  src/argilla/client/feedback/dataset/base.py
  src/argilla/client/feedback/integrations/huggingface/dataset.py
  src/argilla/client/feedback/training/frameworks/openai.py
  src/argilla/client/feedback/training/frameworks/setfit.py
  src/argilla/client/feedback/training/frameworks/spacy.py
  src/argilla/client/feedback/training/frameworks/trl.py
  src/argilla/client/feedback/training/schemas.py
  src/argilla/labeling/text_classification/label_errors.py
  src/argilla/labeling/text_classification/label_models.py
  src/argilla/monitoring/asgi.py
  src/argilla/server/services/tasks/text_classification/metrics.py
  src/argilla/training/autotrain_advanced.py
  src/argilla/training/openai.py
  src/argilla/training/peft.py
  src/argilla/training/setfit.py
  src/argilla/training/spacy.py
  src/argilla/training/span_marker.py
  src/argilla/training/transformers.py
  src/argilla/utils/dependency.py
  tests/unit/utils/test_dependency.py
Labels: enhancement

#3760 feat: update to `fastapi>=0.103.1`
  pyproject.toml
  src/argilla/server/errors/adapter.py
  src/argilla/server/errors/base_errors.py
  src/argilla/server/schemas/v1/responses.py
  tests/unit/server/api/v0/test_datasets.py
  tests/unit/server/api/v1/test_datasets.py
Labels: api, dependencies

#3749 fix: add `draft` status for responses in the Python SDK
  CHANGELOG.md
  src/argilla/client/feedback/integrations/huggingface/dataset.py
  src/argilla/client/feedback/schemas/records.py
  src/argilla/client/sdk/v1/datasets/models.py
  tests/integration/client/feedback/dataset/remote/test_dataset.py
  tests/unit/client/feedback/schemas/test_records.py
Labels: bugfix

#3769 fix: Python 3.11 support due to `Enum` usage
  CHANGELOG.md
  src/argilla/server/apis/v0/handlers/metrics.py
  src/argilla/server/apis/v0/handlers/text2text.py
  src/argilla/server/apis/v0/handlers/text_classification.py
  src/argilla/server/apis/v0/handlers/text_classification_dataset_settings.py
  src/argilla/server/apis/v0/handlers/token_classification.py
  src/argilla/server/apis/v0/handlers/token_classification_dataset_settings.py
  src/argilla/server/daos/backend/query_helpers.py
  src/argilla/server/daos/models/records.py
  src/argilla/server/services/datasets.py
  src/argilla/server/services/tasks/text2text/models.py
  src/argilla/server/services/tasks/token_classification/model.py
Labels: bugfix

#3771 feat: print connected Argilla server URL
  src/argilla/cli/info/__main__.py
  tests/unit/cli/info/test_info.py
Labels: enhancement

#3772 feat: add `server_info` function to check Argilla server info
  CHANGELOG.md
  src/argilla/__init__.py
  src/argilla/cli/info/__main__.py
  src/argilla/client/utils.py
  tests/integration/client/test_utils.py
Labels: enhancement

#3731 :rotating_light: FEAT : highlight field after search
  CHANGELOG.md
  frontend/components/feedback-task/RecordFeedbackTask.component.vue
  frontend/components/feedback-task/field/TextField.component.vue
  frontend/components/feedback-task/field/useTextFieldViewModel.spec.ts
  frontend/components/feedback-task/field/useTextFieldViewModel.ts
  frontend/components/feedback-task/recordFeedbackTask.component.spec.js
Labels: ui

#3777 fix: missing `latest` tag
  .github/workflows/build-push-docker.yml
Labels: ci, bugfix

#3781 fix: `rank=None` when `status=draft`
  CHANGELOG.md
  src/argilla/client/feedback/schemas/records.py
  src/argilla/client/sdk/v1/datasets/models.py
  tests/unit/client/feedback/schemas/test_records.py
Labels: bugfix

#3776 feat: add `VectorSettings` CRUD endpoints
  CHANGELOG.md
  environment_dev.yml
  pyproject.toml
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/apis/v1/handlers/vectors_settings.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/models/models.py
  src/argilla/server/policies.py
  src/argilla/server/routes.py
  src/argilla/server/schemas/v1/datasets.py
  tests/unit/server/api/v1/test_datasets.py
  tests/unit/server/api/v1/test_questions.py
  tests/unit/server/api/v1/test_vectors_settings.py
Labels: enhancement, api

#3793 fix: `quickstart.Dockerfile` after updating `Dockerfile`
  CHANGELOG.md
  docker/Dockerfile
  docker/quickstart.Dockerfile
  docker/scripts/start_quickstart_argilla.sh
Labels: bugfix

#3792 :bug: FIX : restore previous question answer when user go back to same record
  frontend/e2e/annotation-mode-page/__screenshots__/chromium/pending-record-user-submit-and-then-goes-back-to-previous-record-show-updated-answers-1.png
  frontend/e2e/annotation-mode-page/__screenshots__/chromium/pending-record-user-submit-and-then-goes-back-to-previous-record-show-updated-answers-2.png
  frontend/e2e/annotation-mode-page/__screenshots__/chromium/pending-record-user-submit-and-then-goes-back-to-previous-record-show-updated-answers-3.png
  frontend/e2e/annotation-mode-page/__screenshots__/chromium/submitted-record-when-user-ignore-current-modi-58b77-e-record-the-record-have-the-initial-answers-2.png
  frontend/e2e/annotation-mode-page/__screenshots__/chromium/submitted-record-when-user-ignore-current-modi-7cfbe-e-record-the-record-have-the-initial-answers-3.png
  frontend/e2e/annotation-mode-page/__screenshots__/chromium/submitted-record-when-user-ignore-current-modi-85c20-e-record-the-record-have-the-initial-answers-1.png
  frontend/e2e/annotation-mode-page/__screenshots__/chromium/submitted-record-when-user-ignore-current-modi-91e50-e-record-the-record-have-the-initial-answers-4.png
  frontend/e2e/annotation-mode-page/__screenshots__/chromium/submitted-record-when-user-ignore-current-modi-9d326-e-record-the-record-have-the-initial-answers-5.png
  frontend/e2e/annotation-mode-page/__screenshots__/firefox/pending-record-user-submit-and-then-goes-back-to-previous-record-show-updated-answers-1.png
  frontend/e2e/annotation-mode-page/__screenshots__/firefox/pending-record-user-submit-and-then-goes-back-to-previous-record-show-updated-answers-2.png
  frontend/e2e/annotation-mode-page/__screenshots__/firefox/pending-record-user-submit-and-then-goes-back-to-previous-record-show-updated-answers-3.png
  frontend/e2e/annotation-mode-page/__screenshots__/firefox/submitted-record-when-user-ignore-current-modi-58b77-e-record-the-record-have-the-initial-answers-2.png
  frontend/e2e/annotation-mode-page/__screenshots__/firefox/submitted-record-when-user-ignore-current-modi-7cfbe-e-record-the-record-have-the-initial-answers-3.png
  frontend/e2e/annotation-mode-page/__screenshots__/firefox/submitted-record-when-user-ignore-current-modi-85c20-e-record-the-record-have-the-initial-answers-1.png
  frontend/e2e/annotation-mode-page/__screenshots__/firefox/submitted-record-when-user-ignore-current-modi-91e50-e-record-the-record-have-the-initial-answers-4.png
  frontend/e2e/annotation-mode-page/__screenshots__/firefox/submitted-record-when-user-ignore-current-modi-9d326-e-record-the-record-have-the-initial-answers-5.png
  frontend/e2e/annotation-mode-page/__screenshots__/webkit/Annotation-page-shortcuts-Global-shortcuts-For-ef6c1--component-and-the-user-applied-the-read-mode-2.png
  frontend/e2e/annotation-mode-page/__screenshots__/webkit/pending-record-user-submit-and-then-goes-back-to-previous-record-show-updated-answers-1.png
  frontend/e2e/annotation-mode-page/__screenshots__/webkit/pending-record-user-submit-and-then-goes-back-to-previous-record-show-updated-answers-2.png
  frontend/e2e/annotation-mode-page/__screenshots__/webkit/pending-record-user-submit-and-then-goes-back-to-previous-record-show-updated-answers-3.png
  frontend/e2e/annotation-mode-page/__screenshots__/webkit/submitted-record-when-user-ignore-current-modi-58b77-e-record-the-record-have-the-initial-answers-2.png
  frontend/e2e/annotation-mode-page/__screenshots__/webkit/submitted-record-when-user-ignore-current-modi-7cfbe-e-record-the-record-have-the-initial-answers-3.png
  frontend/e2e/annotation-mode-page/__screenshots__/webkit/submitted-record-when-user-ignore-current-modi-85c20-e-record-the-record-have-the-initial-answers-1.png
  frontend/e2e/annotation-mode-page/__screenshots__/webkit/submitted-record-when-user-ignore-current-modi-91e50-e-record-the-record-have-the-initial-answers-4.png
  frontend/e2e/annotation-mode-page/__screenshots__/webkit/submitted-record-when-user-ignore-current-modi-9d326-e-record-the-record-have-the-initial-answers-5.png
  frontend/e2e/annotation-mode-page/autosave-annotation-mode.page.spec.ts
  frontend/v1/domain/entities/question/Question.ts
  frontend/v1/domain/entities/question/QuestionAnswer.ts
  frontend/v1/domain/entities/record/Record.ts
Labels: bug 🪲, ui

#3818 feat: add metadata properties to Python client
  CHANGELOG.md
  src/argilla/__init__.py
  src/argilla/client/feedback/dataset/base.py
  src/argilla/client/feedback/dataset/local.py
  src/argilla/client/feedback/dataset/mixins.py
  src/argilla/client/feedback/dataset/remote/base.py
  src/argilla/client/feedback/dataset/remote/dataset.py
  src/argilla/client/feedback/schemas/__init__.py
  src/argilla/client/feedback/schemas/enums.py
  src/argilla/client/feedback/schemas/metadata.py
  src/argilla/client/feedback/schemas/remote/metadata.py
  src/argilla/client/feedback/schemas/remote/shared.py
  src/argilla/client/feedback/schemas/types.py
  src/argilla/client/feedback/schemas/validators.py
  src/argilla/client/sdk/v1/datasets/api.py
  src/argilla/client/sdk/v1/datasets/models.py
  src/argilla/feedback/__init__.py
  tests/integration/client/feedback/dataset/remote/test_dataset.py
  tests/integration/client/sdk/v1/test_datasets.py
  tests/unit/client/feedback/dataset/test_base.py
  tests/unit/client/feedback/schemas/test_metadata.py
Labels: enhancement, client

#3826 feat: add metadata properties settings backend
  src/argilla/client/feedback/dataset/local.py
  src/argilla/client/feedback/schemas/metadata.py
  src/argilla/client/feedback/schemas/remote/metadata.py
  src/argilla/client/feedback/schemas/validators.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/search_engine.py
  src/argilla/server/search_engine/base.py
  tests/factories.py
  tests/unit/client/feedback/dataset/test_base.py
  tests/unit/client/feedback/schemas/test_metadata.py
  tests/unit/server/api/v1/test_datasets.py
Labels: enhancement, api

#3804 🔦 feat: Metadata filter
  frontend/components/base/base-badge/BaseBadge.vue
  frontend/components/base/base-button/BaseButton.vue
  frontend/components/base/base-checkbox/BaseCheckbox.vue
  frontend/components/base/base-range/BaseRangeMultipleSlider.vue
  frontend/components/feedback-task/container/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/components/feedback-task/container/useRecordFeedbackTaskViewModel.ts
  frontend/components/feedback-task/header/DatasetFilters.component.vue
  frontend/components/feedback-task/header/filters/FilterBadge.vue
  frontend/components/feedback-task/header/filters/FilterTooltip.vue
  frontend/components/feedback-task/header/metadata-filter/MetadataButton.vue
  frontend/components/feedback-task/header/metadata-filter/MetadataCategoriesSelector.vue
  frontend/components/feedback-task/header/metadata-filter/MetadataFilter.vue
  frontend/components/feedback-task/header/metadata-filter/MetadataLabelsSelector.vue
  frontend/components/feedback-task/header/metadata-filter/MetadataLabelsSelectorSearch.vue
  frontend/components/feedback-task/header/metadata-filter/MetadataRangeSelector.vue
  frontend/components/feedback-task/header/metadata-filter/useMetadataFilterViewModel.ts
  frontend/pages/dataset/_id/annotation-mode/index.vue
  frontend/translation/en.json
  frontend/v1/di/di.ts
  frontend/v1/domain/entities/__mocks__/metadata/mock.ts
  frontend/v1/domain/entities/metadata/Metadata.test.ts
  frontend/v1/domain/entities/metadata/Metadata.ts
  frontend/v1/domain/entities/metadata/MetadataFilter.test.ts
  frontend/v1/domain/entities/metadata/MetadataFilter.ts
  frontend/v1/domain/usecases/get-metadata-filters-use-case.ts
  frontend/v1/domain/usecases/get-records-to-annotate-use-case.ts
  frontend/v1/infrastructure/repositories/MetadataRepository.ts
  frontend/v1/infrastructure/repositories/RecordRepository.ts
  frontend/v1/infrastructure/repositories/index.ts
  frontend/v1/infrastructure/services/useRoutes.ts
  frontend/v1/infrastructure/types/index.ts
  frontend/v1/infrastructure/types/metadata.ts
Labels: ui

#3842 docs: add page in the docs describing argilla user roles
  docs/_source/_static/images/installation/user_management/user_roles.png
  docs/_source/getting_started/installation/configurations/user_management.md
Labels: documentation

#3834 feat: add `metadata_filters` to `filter_by` method
  CHANGELOG.md
  src/argilla/__init__.py
  src/argilla/client/feedback/dataset/mixins.py
  src/argilla/client/feedback/dataset/remote/base.py
  src/argilla/client/feedback/dataset/remote/dataset.py
  src/argilla/client/feedback/dataset/remote/filtered.py
  src/argilla/client/feedback/dataset/remote/mixins.py
  src/argilla/client/feedback/schemas/__init__.py
  src/argilla/client/feedback/schemas/metadata.py
  src/argilla/client/feedback/schemas/remote/metadata.py
  src/argilla/client/feedback/schemas/remote/records.py
  src/argilla/client/feedback/schemas/remote/shared.py
  src/argilla/client/feedback/schemas/validators.py
  src/argilla/client/sdk/v1/datasets/api.py
  src/argilla/feedback/__init__.py
  src/argilla/server/contexts/datasets.py
  tests/factories.py
  tests/integration/client/feedback/dataset/remote/test_filtered.py
  tests/integration/client/sdk/v1/test_datasets.py
  tests/unit/client/feedback/schemas/test_metadata.py
  tests/unit/server/api/v1/test_datasets.py
Labels: enhancement, client

#3846 fix: allow `required=False` fields to be logged in Argilla
  CHANGELOG.md
  src/argilla/client/feedback/schemas/records.py
  src/argilla/client/sdk/v1/datasets/api.py
  src/argilla/server/contexts/datasets.py
  tests/unit/client/feedback/schemas/remote/test_records.py
  tests/unit/server/api/v1/test_datasets.py
Labels: client, api, bugfix

#3795 FIX: Correctly save a ArgillaTrainer + TRL model with peft_config
  CHANGELOG.md
  src/argilla/client/feedback/training/frameworks/trl.py
  tests/integration/client/feedback/training/test_trl.py
Labels: bug 🪲, integration, training

#3841 🪖 feat: Sorting component
  frontend/components/feedback-task/container/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/components/feedback-task/container/useRecordFeedbackTaskViewModel.ts
  frontend/components/feedback-task/header/DatasetFilters.component.vue
  frontend/components/feedback-task/header/StatusFilter.vue
  frontend/components/feedback-task/header/filters/FilterButton.vue
  frontend/components/feedback-task/header/metadata-filter/MetadataFilter.vue
  frontend/components/feedback-task/header/metadata-filter/useMetadataFilterViewModel.ts
  frontend/components/feedback-task/header/sort-filter/Sort.vue
  frontend/components/feedback-task/header/sort-filter/SortCategoriesList.vue
  frontend/components/feedback-task/header/sort-filter/SortSelector.vue
  frontend/components/feedback-task/header/sort-filter/SortSelectorItem.vue
  frontend/components/feedback-task/header/sort-filter/useSortRecords.ts
  frontend/components/feedback-task/header/useDatasetsFiltersViewModel.ts
  frontend/v1/di/di.ts
  frontend/v1/domain/entities/metadata/MetadataSort.ts
  frontend/v1/domain/usecases/get-metadata-use-case.ts
  frontend/v1/domain/usecases/get-records-to-annotate-use-case.ts
  frontend/v1/infrastructure/repositories/RecordRepository.ts
Labels: ui

#3843 feat: add `sort_by` query param to listing record endpoints
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/enums.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/search_engine/base.py
  src/argilla/server/search_engine/commons.py
  src/argilla/server/utils.py
  tests/unit/server/api/v1/test_datasets.py
  tests/unit/server/test_utils.py
Labels: enhancement, api
