Repository argilla-io/argilla, pull requests merged in 2023-06, with the labels that each got.

#3055 feat: check duplicated values for rating, label selection and multi label selection questions
  src/argilla/server/models/questions.py
  src/argilla/server/schemas/v1/datasets.py
  tests/server/api/v1/test_datasets.py
Labels: enhancement, api

#3056 fix: wrong `FeedbackDatasetConfig` parsing in `from_huggingface`
  src/argilla/client/feedback/schemas.py
  tests/client/feedback/test_dataset.py
Labels: bugfix

#3016 :sparkles: Feat : single choice component
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/commons/forms/questions-form/fields/single-label/SingleLabel.component.vue
  frontend/components/commons/forms/questions-form/fields/single-label/SingleLabelMonoSelection.component.vue
  frontend/components/commons/forms/questions-form/fields/single-label/search-single-label/SearchSingleLabel.component.vue
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/models/feedback-task-model/dataset-question/DatasetQuestion.model.js
Labels: ui

#3060 docs: add `ArgillaCallbackHandler` guide for `LangChain`-integration
  docs/_source/_static/images/llms/langchain-integration/agent.png
  docs/_source/_static/images/llms/langchain-integration/chain.png
  docs/_source/_static/images/llms/langchain-integration/llm.png
  docs/_source/guides/llms/practical_guides/practical_guides.md
  docs/_source/guides/llms/practical_guides/use_argilla_callback_in_langchain.md
Labels: documentation

#3033 feat: add `draft` status to `Response`
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/models/models.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/schemas/v1/records.py
  tests/server/api/v1/test_datasets.py
  tests/server/api/v1/test_records.py
Labels: enhancement, api

#3068 feat: add `FeedbackDataset` search endpoint
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/enums.py
  src/argilla/server/policies.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/search_engine.py
  tests/server/api/v1/test_datasets.py
Labels: enhancement, api

#3011 build: add `tests` extras & update `developer_docs.md`
  docs/_source/community/developer_docs.md
  environment_dev.yml
  pyproject.toml
  src/argilla/monitoring/_flair.py
  src/argilla/training/setfit.py
  src/argilla/training/utils.py
  tests/monitoring/test_flair_monitoring.py
  tests/training/helpers.py
Labels: documentation, tests

#3114 :bug: FIX : Update criteria to show search
  frontend/components/feedback-task/feedbackTask.properties.js
Labels: bug 🪲, ui

#3100 feat: add `LabelQuestion` and `MultiLabelQuestion` in Python client
  src/argilla/__init__.py
  src/argilla/client/feedback/dataset.py
  src/argilla/client/feedback/schemas.py
  src/argilla/client/sdk/v1/datasets/models.py
  tests/client/conftest.py
  tests/client/feedback/test_dataset.py
  tests/client/feedback/test_schemas.py
Labels: client

#3124 :bug: FIX : allow access to metrix when no records for current queue
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
Labels: bug 🪲, ui

#3126 fix: allow `visible_labels=None` & disallow `fields`/`questions` with the same name
  CHANGELOG.md
  src/argilla/client/feedback/dataset.py
  src/argilla/client/feedback/schemas.py
  tests/client/feedback/test_dataset.py
  tests/client/feedback/test_schemas.py
Labels: bugfix

#3110 style: curate auto-generated `DatasetCard` for `FeedbackDataset`
  CHANGELOG.md
  pyproject.toml
  src/argilla/client/feedback/card/__init__.py
  src/argilla/client/feedback/card/_dataset_card.py
  src/argilla/client/feedback/card/_parser.py
  src/argilla/client/feedback/card/argilla_template.md
  src/argilla/client/feedback/dataset.py
  src/argilla/client/feedback/schemas.py
  src/argilla/client/feedback/utils.py
  tests/client/conftest.py
  tests/client/feedback/test_card.py
Labels: client, integration

#3125 chore: updated docs dependencies
  docs/_source/_common/steps_points.md
  docs/_source/_common/tabs/records_create.md
  docs/_source/_common/tasks_points.md
  docs/_source/_common/techniques_points.md
  docs/_source/conf.py
  docs/_source/getting_started/cheatsheet.md
  docs/_source/getting_started/installation/configurations/configurations.md
  docs/_source/getting_started/installation/configurations/elasticsearch.md
  docs/_source/getting_started/installation/deployments/deployments.md
  docs/_source/getting_started/installation/installation.md
  docs/_source/getting_started/quickstart.md
  docs/_source/guides/label_records_with_semanticsearch.ipynb
  docs/_source/guides/llms/conceptual_guides/conceptual_guides.md
  docs/_source/guides/llms/examples/examples.md
  docs/_source/guides/llms/examples/rating.md
  docs/_source/guides/llms/examples/rlhf.md
  docs/_source/guides/llms/examples/supervised.md
  docs/_source/guides/llms/practical_guides/practical_guides.md
  docs/_source/guides/log_load_and_prepare_data.ipynb
  docs/_source/guides/log_load_and_prepare_data.md
  docs/_source/guides/query_datasets.md
  docs/_source/index.rst
  docs/_source/reference/webapp/pages.md
  docs/_source/requirements.txt
  docs/_source/tutorials/libraries/libraries.md
  docs/_source/tutorials/steps/steps.md
  docs/_source/tutorials/tasks/tasks.md
  docs/_source/tutorials/techniques/techniques.md
Labels: documentation

#3132 [Docs] Clean up TRL tutorial
  docs/_source/guides/llms/examples/train-reward-model-rlhf.ipynb
Labels: documentation

#3142 :heavy_plus_sign: Add Dependency : babel dependency import
  frontend/package.json
Labels: ui, dependencies

#3138 :sparkles: FEAT: Search for feedbacktask
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/feedback-task/DatasetFilters.component.vue
  frontend/components/feedback-task/RadioButtonsSelect.base.vue
  frontend/components/feedback-task/SearchBar.base.vue
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/pages/dataset/_id/annotation-mode/index.vue
Labels: ui

#3173 :sparkles: FEAT : add `total_records` when search is apply
  frontend/components/feedback-task/DatasetFilters.component.vue
  frontend/components/feedback-task/SearchBar.base.vue
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
Labels: ui

#3174 fix: unhandled `ImportError` on `huggingface_hub`
  CHANGELOG.md
  src/argilla/client/feedback/dataset.py
Labels: bugfix

#3185 Docs: typo, AutoTrai -> AutoTrain
  docs/_source/guides/train_a_model.md
Labels: documentation

#3190 :bug: FIX : correction in search logic
  frontend/components/feedback-task/SearchBar.base.vue
Labels: bug 🪲, ui

#3207 chore: split `integrations` and `tests` dependencies
  docs/_source/_common/tabs/argilla_install_python.md
  docs/_source/community/developer_docs.md
  docs/_source/getting_started/installation/deployments/python.md
  pyproject.toml
Labels: dependencies

#3214 fix: `find_label_errors` raising `AttributeError` with `numpy>=1.24.0`
  CHANGELOG.md
  src/argilla/labeling/text_classification/label_errors.py
  tests/labeling/text_classification/test_label_errors.py
Labels: bug 🪲, client

#3222 chore: drop Python 3.7 support due to its close EOL
  CHANGELOG.md
  pyproject.toml
  src/argilla/__init__.py
  src/argilla/client/feedback/dataset.py
  src/argilla/client/feedback/schemas.py
  src/argilla/client/sdk/v1/datasets/models.py
  src/argilla/client/sdk/workspaces/models.py
  src/argilla/server/models/questions.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/schemas/v1/fields.py
  src/argilla/server/schemas/v1/questions.py
  src/argilla/server/schemas/v1/responses.py
Labels: deprecation

#3231 fix: `push_to_huggingface` parsing of UUIDs
  src/argilla/client/feedback/dataset.py
  src/argilla/client/feedback/utils.py
Labels: bugfix

#3224 fix: `format_as("datasets")` when no responses
  CHANGELOG.md
  src/argilla/client/feedback/dataset.py
  src/argilla/client/feedback/utils.py
  tests/client/conftest.py
Labels: bugfix

#3234 fix: `push_to_argilla` and `from_argilla` consistency issues
  CHANGELOG.md
  src/argilla/client/feedback/dataset.py
  src/argilla/client/sdk/v1/datasets/api.py
  tests/client/feedback/test_dataset.py
Labels: bugfix

#3236 docs: add `User` and `Workspace` management layers
  docs/_source/getting_started/installation/configurations/configurations.md
  docs/_source/getting_started/installation/configurations/user_management.md
  docs/_source/getting_started/installation/configurations/workspace_management.md
  docs/_source/guides/llms/practical_guides/set_up_annotation_team.md
  docs/_source/reference/python/index.rst
  docs/_source/reference/python/python_client.rst
  docs/_source/reference/python/python_users.rst
  docs/_source/reference/python/python_workspaces.rst
Labels: documentation

#3208 fix: Render correctly markdown
  frontend/components/base/render-markdown/RenderMarkdown.base.component.vue
  frontend/components/base/render-markdown/renderMarkdown.base.component.spec.js
  frontend/components/text2text/results/ContentEditableFeedbackTask.vue
Labels: bug 🪲, ui

#3239 docs: update docs prior 1.11.0 release
  docs/_source/_common/tabs/records_create.md
  docs/_source/getting_started/installation/configurations/configurations.md
  docs/_source/getting_started/installation/configurations/user_management.md
  docs/_source/getting_started/installation/configurations/workspace_management.md
  docs/_source/guides/llms/examples/curating-feedback-instructiondataset.ipynb
  docs/_source/guides/llms/practical_guides/set_up_annotation_team.md
  docs/_source/reference/python/index.rst
  docs/_source/reference/python/python_client.rst
  docs/_source/reference/python/python_users.rst
  docs/_source/reference/python/python_workspaces.rst
  src/argilla/client/sdk/workspaces/models.py
Labels: documentation

#3249 feat: create `/data` directory in quickstart Docker image
  quickstart.Dockerfile
Labels: enhancement

#3232 feat: add Ranking Question to the API
  CHANGELOG.md
  src/argilla/server/models/questions.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/search_engine.py
  tests/factories.py
  tests/server/api/v1/test_datasets.py
  tests/server/api/v1/test_records.py
Labels: enhancement, api

#3289 feat: warn user when trying to load `FeedbackDataset` using `rg.load`
  CHANGELOG.md
  src/argilla/client/api.py
  tests/client/test_api.py
Labels: client

#3177 :sparkles: FEAT : Ranking component
  frontend/assets/icons/draggable.js
  frontend/assets/icons/index.js
  frontend/assets/scss/abstract/variables/_variables.scss
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/commons/forms/questions-form/fields/ranking/Ranking.component.vue
  frontend/components/commons/forms/questions-form/fields/ranking/ranking-adapter.js
  frontend/components/commons/forms/questions-form/fields/ranking/ranking-adapter.test.js
  frontend/components/commons/forms/questions-form/fields/ranking/ranking-fakes.js
  frontend/components/commons/forms/questions-form/fields/ranking/ranking.component.spec.js
  frontend/components/commons/forms/questions-form/fields/rating/rating.component.spec.js
  frontend/components/commons/forms/questions-form/fields/shared-components/drag-and-drop-selection/DndSelection.component.vue
  frontend/components/commons/forms/questions-form/fields/shared-components/drag-and-drop-selection/dndSelection.component.spec.js
  frontend/components/commons/forms/questions-form/questionsForm.component.spec.js
  frontend/components/feedback-task/feedbackTask.properties.js
  frontend/components/feedback-task/recordFeedbackTask.component.spec.js
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/components/page-contents/feedback-task-content/centerFeedbackTask.component.spec.js
  frontend/nuxt.config.js
  frontend/package.json
  frontend/plugins/vue-draggable.js
  frontend/static/icons/draggable.svg
Labels: ui

#3256 feat: add `ArgillaSpaCyTransformersTrainer` & improve `ArgillaSpaCyTrainer`
  environment_dev.yml
  pyproject.toml
  src/argilla/client/datasets.py
  src/argilla/client/feedback/dataset.py
  src/argilla/client/feedback/training/base.py
  src/argilla/client/feedback/training/frameworks/spacy.py
  src/argilla/client/feedback/training/schemas.py
  src/argilla/client/models.py
  src/argilla/training/base.py
  src/argilla/training/spacy.py
  tests/client/feedback/test_dataset.py
  tests/client/feedback/training/test_schemas.py
  tests/client/feedback/training/test_trainer.py
  tests/training/test_spacy.py
Labels: integration

#3293 Docs: add ranking question documentation
  docs/_source/_common/tabs/dataset_settings.md
  docs/_source/_common/tabs/question_settings.md
  docs/_source/_common/tabs/unfication_strategies.md
  docs/_source/_static/images/llms/fb-model.svg
  docs/_source/_static/images/llms/questions/ranking_question.png
  docs/_source/getting_started/cheatsheet.md
  docs/_source/guides/llms/conceptual_guides/data_model.md
  docs/_source/guides/llms/conceptual_guides/rm.md
  docs/_source/guides/llms/practical_guides/collect_responses.md
  docs/_source/guides/llms/practical_guides/create_dataset.md
Labels: documentation
