Repository argilla-io/argilla, pull requests merged in 2023-04, with the labels that each got.

#2652 feat : hide user settings token
  frontend/components/commons/user-token/UserToken.component.vue
Labels: ui

#2635 enhancement: Add `stacklevel` to warning in metrics method
  src/argilla/metrics/models.py
Labels: enhancement, Metrics

#2672 feat : front instructions task
  frontend/layouts/HeaderAndTopAndOneColumn.vue
Labels: ui

#2692 feat: Include sidebar for Feedback Task
  frontend/components/commons/sidebar-feedback-task/IconButton.vue
  frontend/components/commons/sidebar-feedback-task/SidebarFeedbackTask.component.vue
  frontend/components/commons/sidebar-feedback-task/SidebarFeedbackTask.vue
  frontend/components/commons/sidebar-feedback-task/SidebarFeedbackTaskButtonGroup.vue
  frontend/components/commons/sidebar-feedback-task/SidebarFeedbackTaskPanel.vue
  frontend/components/commons/sidebar-feedback-task/SidebarFeedbackTaskProgress.vue
  frontend/components/feedback-task/FeedbackTaskProgress.vue
Labels: ui

#2680 feat : front orm model instruction task
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/commons/forms/questions-form/fields/mono-selection/MonoSelection.component.vue
  frontend/components/commons/forms/questions-form/fields/rating/Rating.component.vue
  frontend/components/commons/forms/questions-form/fields/single-label/SingleLabel.component.vue
  frontend/components/commons/forms/questions-form/fields/text-area/TextArea.component.vue
  frontend/components/commons/header/header-feedback-task/HeaderFeedbackTask.component.vue
  frontend/components/feedback-task/RecordFeedbackTask.component.vue
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
  frontend/database/index.js
  frontend/models/feedback-task-model/dataset-question/DatasetQuestion.model.js
  frontend/models/feedback-task-model/dataset-question/datasetQuestion.queries.js
  frontend/models/feedback-task-model/feedback-dataset/FeedbackDataset.model.js
  frontend/models/feedback-task-model/feedback-dataset/feedbackDataset.queries.js
  frontend/models/feedback-task-model/record-field/RecordField.model.js
  frontend/models/feedback-task-model/record-response/RecordResponse.model.js
  frontend/models/feedback-task-model/record-response/recordResponse.queries.js
  frontend/models/feedback-task-model/record/Record.model.js
  frontend/models/feedback-task-model/record/record.queries.js
  frontend/pages/dataset/_id/annotation-mode/index.vue
Labels: ui

#2727 feat : get workspace name instruction task
  frontend/pages/dataset/_id/annotation-mode/index.vue
Labels: ui

#2728 feat: integrate new instruction task in datasets list page
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
  frontend/database/modules/datasets.js
  frontend/models/dataset.utilities.js
  frontend/models/feedback-task-model/feedback-dataset/feedbackDataset.queries.js
  frontend/pages/datasets/index.vue
Labels: ui

#2747 docs: assignments tutorial notebook
  docs/_source/_static/tutorials/labelling-textclassification-sentencetransformers-semantic/modal.md
  docs/_source/_static/tutorials/labelling-tokenclassification-basics/labelling-tokenclassification-basics-screenshot.png
  docs/_source/_static/tutorials/labelling-tokenclassification-basics/modal.md
  docs/_source/tutorials/notebooks/labelling-tokenclassification-basics.ipynb
  docs/_source/tutorials/steps/1_labelling.md
  docs/_source/tutorials/techniques/1_basics.md
Labels: documentation

#2745 [Docs] Improve monitoring docs
  docs/_source/conf.py
  docs/_source/reference/python/python_monitoring.rst
  src/argilla/monitoring/model_monitor.py
  tests/monitoring/test_monitor.py
Labels: documentation

#2805 feat : navigate with shortcut feedback task
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/feedback-task/footer/Pagination.component.vue
  frontend/components/text2text/results/Text2TextContentEditable.vue
Labels: ui
