Repository argilla-io/argilla, pull requests merged in 2023-07, with the labels that each got.

#3302 🚑 Fix dependencies
  frontend/package.json
Labels: ui

#3307 fix: unit test failing if not local db
  .github/workflows/run-python-tests.yml
  CHANGELOG.md
  src/argilla/server/server.py
  tests/conftest.py
Labels: bug 🪲

#3308 feat: add list user workspaces endpoint
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/users.py
  src/argilla/server/contexts/accounts.py
  src/argilla/server/policies.py
  src/argilla/server/routes.py
  src/argilla/server/schemas/v1/workspaces.py
  tests/server/api/v1/test_users.py
Labels: enhancement, api

#3334 feat: add `list_user_workspaces` and `User.workspaces` property
  CHANGELOG.md
  src/argilla/client/sdk/users/models.py
  src/argilla/client/sdk/v1/users/__init__.py
  src/argilla/client/sdk/v1/users/api.py
  src/argilla/client/sdk/v1/users/models.py
  src/argilla/client/users.py
  tests/client/sdk/users/test_api.py
  tests/client/sdk/v1/users/__init__.py
  tests/client/sdk/v1/users/test_api.py
  tests/client/sdk/workspaces/test_api.py
  tests/client/test_users.py
Labels: client

#3304 feat: add `Suggestion` endpoints
  CHANGELOG.md
  src/argilla/server/alembic/versions/3fc3c0839959_create_suggestions_table.py
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/apis/v1/handlers/records.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/models/models.py
  src/argilla/server/models/questions.py
  src/argilla/server/policies.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/schemas/v1/suggestions.py
  tests/factories.py
  tests/server/api/v1/test_datasets.py
  tests/server/api/v1/test_records.py
Labels: bug 🪲, enhancement, api

#3327 Feat/update start page code
  docs/_source/_common/snippets/start_page.md
  frontend/README.md
  frontend/components/base/base-tabs/BaseTabs.vue
  frontend/components/base/documentation-viewer/DocumentationViewer.vue
  frontend/components/commons/dataset-train/DatasetTrain.component.vue
  frontend/components/commons/datasets-list/DatasetsEmpty.vue
  frontend/nuxt.config.js
  frontend/pages/datasets/index.vue
Labels: documentation, ui

#3349 fix: Set pydantic < 2.0
  CHANGELOG.md
  docs/_source/.readthedocs.yaml
  docs/_source/reference/python/python_client.rst
  docs/_source/reference/python/python_training.rst
  pyproject.toml
Labels: bugfix

#3328 feat: warn users when using integer record ids
  CHANGELOG.md
  src/argilla/_constants.py
  src/argilla/client/models.py
  src/argilla/server/daos/backend/client_adapters/opensearch.py
  src/argilla/server/daos/models/records.py
  tests/client/sdk/text2text/test_models.py
  tests/client/test_models.py
  tests/server/token_classification/test_model.py
Labels: bugfix

#3353 🎉 Add user workspaces into user setting page
  .github/workflows/build-python-package.yml
  environment_dev.yml
  frontend/components/commons/edition-user-info/EditionUserInfo.component.vue
Labels: ui

#3366 fix: `ArgillaDatasetCard` to handle all question `options`
  CHANGELOG.md
  src/argilla/client/feedback/integrations/huggingface/card/argilla_template.md
Labels: bugfix

#3375 fix: `deploy_docker` execution condition
  .github/workflows/package.yml
Labels: bug 🪲, ci

#3381 fix: `HuggingFaceDatasetMixIn` dependencies and usage
  src/argilla/client/feedback/dataset.py
  src/argilla/client/feedback/integrations/huggingface/dataset.py
  tests/client/feedback/test_dataset.py
Labels: dependencies, bugfix

#3383 feat: add `allowed_for_roles` decorator in `User` and `Workspace`
  CHANGELOG.md
  src/argilla/client/users.py
  src/argilla/client/utils.py
  src/argilla/client/workspaces.py
  tests/client/test_api.py
  tests/client/test_users.py
  tests/client/test_workspaces.py
Labels: enhancement

#3385 :bug: FIX : Ensure current user is disconnected when going to login page
  frontend/components/commons/header/header-feedback-task/headerFeedbackTask.spec.js
  frontend/pages/login.vue
Labels: bug 🪲, client

#3356 feat: add CRUD for SQLAlchemy models
  src/argilla/server/alembic/env.py
  src/argilla/server/apis/v0/handlers/users.py
  src/argilla/server/contexts/accounts.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/database.py
  src/argilla/server/models/base.py
  src/argilla/server/models/mixins.py
  src/argilla/server/models/models.py
  tests/client/feedback/test_dataset.py
  tests/conftest.py
  tests/factories.py
  tests/server/api/v1/test_datasets.py
  tests/server/models/__init__.py
  tests/server/models/test_base.py
Labels: enhancement, api

#3390 feat: add GET `/api/v1/me/workspaces` & update `Workspace` class
  CHANGELOG.md
  src/argilla/client/sdk/users/api.py
  src/argilla/client/sdk/v1/users/api.py
  src/argilla/client/sdk/v1/workspaces/api.py
  src/argilla/client/users.py
  src/argilla/client/utils.py
  src/argilla/client/workspaces.py
  src/argilla/server/apis/v1/handlers/users.py
  src/argilla/server/apis/v1/handlers/workspaces.py
  src/argilla/server/policies.py
  tests/client/sdk/v1/users/test_api.py
  tests/client/sdk/v1/workspaces/__init__.py
  tests/client/sdk/v1/workspaces/test_api.py
  tests/client/sdk/v1/workspaces/test_models.py
  tests/client/test_users.py
  tests/client/test_workspaces.py
  tests/server/api/v1/test_users.py
  tests/server/api/v1/test_workspaces.py
Labels: enhancement, bugfix

#3370 feat: add `suggestions` in `FeedbackRecord`
  CHANGELOG.md
  src/argilla/client/feedback/dataset.py
  src/argilla/client/feedback/integrations/huggingface/card/argilla_template.md
  src/argilla/client/feedback/integrations/huggingface/dataset.py
  src/argilla/client/feedback/schemas.py
  src/argilla/client/sdk/v1/datasets/api.py
  src/argilla/client/sdk/v1/datasets/models.py
  tests/client/conftest.py
  tests/client/feedback/test_dataset.py
  tests/client/sdk/v1/datasets/test_api.py
Labels: enhancement

#3408 :bug: FIX : fields from feedback task => break word when too long
  frontend/components/feedback-task/field/TextField.component.vue
Labels: bug 🪲, ux, ui

#3412 :bug: FIX : add missing data `datasetId` on delete dataset
  frontend/components/commons/dataset-deletion-feedback-task/DatasetDeleteFeedbackTask.component.vue
Labels: bug 🪲, ui

#3432 docs: fix username in HF Spaces docs
  docs/_source/getting_started/installation/deployments/huggingface-spaces.md
Labels: documentation

#3443 docs: Resolve typos, missing import
  docs/_source/guides/train_a_model.md
Labels: documentation

#3458 fix: uncancellable CI jobs
  .github/workflows/build-python-package.yml
  .github/workflows/check-repo-files.yml
  .github/workflows/package.yml
  .github/workflows/run-python-tests.yml
  .github/workflows/tutorials.yml
Labels: ci

#3422 feat: update `package.yml` triggers
  .github/workflows/package.yml
Labels: ci

#3450 feat: update CLI to use async connection to DB
  CHANGELOG.md
  src/argilla/__main__.py
  src/argilla/server/alembic/env.py
  src/argilla/server/apis/v1/handlers/responses.py
  src/argilla/server/database.py
  src/argilla/server/seeds.py
  src/argilla/server/settings.py
  src/argilla/tasks/async_typer.py
  src/argilla/tasks/database/migrate.py
  src/argilla/tasks/database/revisions.py
  src/argilla/tasks/training/__main__.py
  src/argilla/tasks/users/__main__.py
  src/argilla/tasks/users/create.py
  src/argilla/tasks/users/create_default.py
  src/argilla/tasks/users/migrate.py
  src/argilla/tasks/users/update.py
  src/argilla/tasks/users/utils.py
  tests/conftest.py
  tests/factories.py
  tests/server/commons/test_settings.py
  tests/tasks/conftest.py
  tests/tasks/users/conftest.py
  tests/tasks/users/test_create.py
  tests/tasks/users/test_create_default.py
  tests/tasks/users/test_update.py
Labels: client, api

#3469 feat: add `get_metrics` function in SDK
  CHANGELOG.md
  src/argilla/client/sdk/v1/datasets/api.py
  src/argilla/client/sdk/v1/datasets/models.py
  tests/client/sdk/v1/datasets/test_api.py
Labels: enhancement

#3402 feat: add dataset `PATCH` endpoint
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/policies.py
  src/argilla/server/schemas/v1/datasets.py
  tests/server/api/v1/test_datasets.py
Labels: enhancement, api

#3421 feat: field `PATCH` endpoint
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/fields.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/models/mixins.py
  src/argilla/server/models/models.py
  src/argilla/server/policies.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/schemas/v1/fields.py
  tests/factories.py
  tests/server/api/v1/test_fields.py
Labels: enhancement, api
