Repository argilla-io/argilla, pull requests merged in 2023-02, with the labels that each got.

#2225 feat: updated the prepare_for_training methods
  .pre-commit-config.yaml
  docs/_source/guides/features/datasets.ipynb
  elasticsearch_vector_search_use_case.ipynb
  src/argilla/client/datasets.py
  src/argilla/client/models.py
  tests/client/test_dataset.py
Labels: documentation, api

#2286 Docs: Replace leftover `rubrix.apikey` with `argilla.apikey`
  src/argilla/client/client.py
Labels: documentation

#2287 Docs: Remove cut-off sentence in docs codeblock
  docs/_source/getting_started/installation/user_management.md
Labels: documentation

#2285 Fix broken `.pre-commit-config.yaml` configuration
  .pre-commit-config.yaml
Labels: ci

#2242 feat(Client): relax client constraints for rules management
  src/argilla/client/client.py
  tests/labeling/text_classification/test_rule.py
Labels: enhancement, client, Automatic Labeling

#2305 docs: Rephrase `to know more` into `to learn more` in Quickstart login page
  frontend/pages/login.vue
Labels: documentation

#2316 resolved prepare_for_training errors prior to release w.r.t. inputs f…
  src/argilla/client/datasets.py
  tests/client/test_dataset.py
Labels: bug

#2322 Docs: Simplify token attributions code block
  docs/_source/guides/log_model_explanations.md
Labels: documentation

#2289 Replace Rubrix Docker link with updated Argilla one
  docs/_source/getting_started/installation/configurations/user_management.md
Labels: documentation

#2337 Enhancement: Also validate records on assignment of variables
  src/argilla/client/models.py
  tests/client/test_models.py
Labels: enhancement, client

#2358 ci: Remove Pyre from CI
  .github/workflows/pyre-check.yml
  .pyre_configuration
Labels: ci

#2392 CI: Skip rather than failing in 2 common scenarios
  .github/workflows/package.yml
Labels: ci

#2411 resolved #2406 #2407 #2408 #2405
  docs/_source/guides/log_load_and_prepare_data.ipynb
  src/argilla/client/datasets.py
  tests/client/test_dataset.py
Labels: bug, enhancement

#2393 Refactor: Replace "ar" with "rg" in test imports
  docs/_source/conf.py
  tests/client/conftest.py
  tests/client/sdk/conftest.py
  tests/client/test_api.py
  tests/client/test_client_errors.py
  tests/client/test_dataset.py
  tests/datasets/test_datasets.py
  tests/functional_tests/datasets/helpers.py
  tests/functional_tests/datasets/test_delete_records_from_datasets.py
  tests/functional_tests/test_log_for_text_classification.py
  tests/labeling/text_classification/test_label_errors.py
  tests/labeling/text_classification/test_rule.py
  tests/listeners/test_listener.py
  tests/metrics/test_common_metrics.py
  tests/metrics/test_text_classification.py
  tests/metrics/test_token_classification.py
  tests/monitoring/test_flair_monitoring.py
  tests/monitoring/test_spacy_monitoring.py
  tests/server/text_classification/test_api_settings.py
  tests/server/token_classification/test_api_settings.py
Labels: tests

#2339 Enhancement: extend shortcuts to include alphabet for token classification
  frontend/components/token-classifier/header/EntitiesHeader.vue
  frontend/components/token-classifier/results/TextSpan.vue
Labels: enhancement
