Repository argilla-io/argilla, pull requests merged in 2023-11, with the labels that each got.

#4113 fix: avoid installing `pytest-asyncio==0.22.0`
  environment_dev.yml
Labels: dependencies, bugfix

#4112 feat: allow updating `allow_extra_metadata`
  CHANGELOG.md
  src/argilla/server/schemas/v1/datasets.py
  tests/unit/server/api/v1/test_datasets.py
Labels: enhancement, api

#4104 feat: enhance `PATCH` record endpoints for updating vectors
  src/argilla/server/contexts/datasets.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/schemas/v1/vectors.py
  tests/integration/client/feedback/dataset/remote/test_dataset.py
  tests/unit/server/api/v1/test_datasets.py
  tests/unit/server/api/v1/test_records.py
Labels: enhancement, api

#4130 feat: add `delete_vectors_settings` method
  CHANGELOG.md
  src/argilla/client/feedback/dataset/local/dataset.py
  src/argilla/client/feedback/dataset/remote/dataset.py
  src/argilla/client/sdk/v1/vectors_settings/api.py
  tests/integration/client/feedback/dataset/remote/test_dataset.py
  tests/unit/client/feedback/dataset/local/test_dataset.py
  tests/unit/client/sdk/v1/vectors_settings/test_api.py
Labels: enhancement, client

#4074 feat: add `max_records` argument to `pull()` method `RemoteFeedbackDataset` #4072
  .pre-commit-config.yaml
  CHANGELOG.md
  docs/_source/practical_guides/export_dataset.md
  src/argilla/client/feedback/dataset/local/dataset.py
  src/argilla/client/feedback/dataset/remote/dataset.py
  tests/integration/client/feedback/dataset/remote/test_dataset.py
  tests/integration/client/feedback/dataset/remote/test_filter_and_sorting.py
Labels: machine-learning

#4044 feat: Add metadata properties to dataset card
  src/argilla/client/feedback/integrations/huggingface/card/argilla_template.md
  src/argilla/client/feedback/integrations/huggingface/dataset.py
  tests/unit/client/feedback/integrations/huggingface/card/test__dataset_card.py
Labels: hacktoberfest-accepted

#4129 docs: vectors and semantic search in Feedback Datasets
  docs/_source/_common/sdk_feedback_semantic_search.md
  docs/_source/_common/ui_feedback_semantic_search.md
  docs/_source/_static/images/llms/feedback_semantic_search.png
  docs/_source/_static/images/llms/snapshot-feedback-demo.png
  docs/_source/_static/images/llms/snapshot-feedback-submitted.png
  docs/_source/getting_started/installation/configurations/server_configuration.md
  docs/_source/practical_guides/annotate_dataset.md
  docs/_source/practical_guides/annotation_workflows/semantic_search.ipynb
  docs/_source/practical_guides/annotation_workflows/semantic_search.md
  docs/_source/practical_guides/choose_dataset.md
  docs/_source/practical_guides/create_dataset.md
  docs/_source/practical_guides/export_dataset.md
  docs/_source/practical_guides/filter_dataset.md
Labels: documentation, feedback-dataset

#4203 fix: safer dump of `vectors` in the HuggingFace Hub
  src/argilla/client/feedback/integrations/huggingface/dataset.py
  tests/integration/client/feedback/integrations/huggingface/test_dataset.py
Labels: bugfix

#4166 docs: Add Changelog section to Contributor Documentation
  docs/_source/community/contributing.md
Labels: documentation

#4305 feat: Using new filters mechanism with `search` method
  src/argilla/server/search_engine/base.py
  src/argilla/server/search_engine/commons.py
  src/argilla/server/search_engine/elasticsearch.py
  src/argilla/server/search_engine/opensearch.py
  tests/unit/server/search_engine/test_elasticsearch_engine.py
  tests/unit/server/search_engine/test_opensearch_engine.py
Labels: size:L, lgtm

#4261 docs: revisit install process
  docs/_source/community/developer_docs.md
  docs/_source/reference/terminology.md
Labels: size:L, lgtm

#4306 feat: add validations for records search filters and sort
  src/argilla/errors.py
  src/argilla/server/apis/v1/handlers/datasets/records.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/contexts/search.py
  src/argilla/server/errors/future/__init__.py
  src/argilla/server/errors/future/base_errors.py
  src/argilla/server/schemas/v1/datasets.py
  tests/factories.py
  tests/unit/server/api/v1/datasets/test_search_current_user_dataset_records.py
  tests/unit/server/api/v1/datasets/test_search_dataset_records.py
  tests/unit/server/contexts/__init__.py
  tests/unit/server/contexts/search/__init__.py
  tests/unit/server/contexts/search/test_search_records_query_validator.py
Labels: size:XL, lgtm

#4309 feat: using new filters for `similarity_search` method
  src/argilla/server/search_engine/commons.py
  src/argilla/server/search_engine/elasticsearch.py
  src/argilla/server/search_engine/opensearch.py
Labels: size:L, lgtm

#4311 refactor: change filter `and` operator to be mandatory instead of optional
  src/argilla/server/contexts/search.py
  src/argilla/server/schemas/v1/datasets.py
Labels: size:XS

#4303 feat: new pagination UI
  frontend/components/feedback-task/container/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/components/feedback-task/container/fields/RecordFieldsAndSimilarity.vue
  frontend/components/feedback-task/container/questions/form/text-area/TextArea.component.vue
  frontend/components/feedback-task/footer/Pagination.component.vue
  frontend/components/feedback-task/footer/PaginationFeedbackTask.component.vue
  frontend/components/feedback-task/header/DatasetFilters.component.vue
  frontend/layouts/HeaderAndTopAndOneColumn.vue
  frontend/pages/dataset/_id/annotation-mode/index.vue
Labels: size:L

#4313 docs: Adding `metadata` to a `text-classification` dataset
  docs/_source/_static/tutorials/end2end/text-classification/argilla-ui-page-metadata.png
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-metadata-003.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/configure-users-and-workspaces-000.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/create-dataset-001.ipynb
  docs/_source/tutorials_and_integrations/tutorials/tutorials.md
Labels: size:XL

#4314 fix: update to solve the error of integration tests in CI
  .github/workflows/run-python-tests.yml
  src/argilla/training/base.py
  tests/integration/client/feedback/training/test_trainer.py
Labels: type: bug, area: ci, language: python, team: backend, size:M, lgtm

#4295 fix: correct unification implementation for `RankingQuestionStrategy`
  CHANGELOG.md
  src/argilla/client/feedback/unification.py
  tests/integration/client/feedback/test_unification.py
Labels: size:L, lgtm

#4315 Update labels in github workflows
  .github/workflows/close-inactive-issues-bot.yml
Labels: area: ci, type: improvement, size:XS, lgtm

#4318 tests: Unify search engine tests into a single test suite
  tests/unit/server/search_engine/conftest.py
  tests/unit/server/search_engine/test_commons.py
  tests/unit/server/search_engine/test_elasticsearch_engine.py
  tests/unit/server/search_engine/test_elastisearch.py
  tests/unit/server/search_engine/test_opensearch.py
Labels: area: tests, language: python, type: refactor, team: backend, size:XXL, lgtm

#4310 feat: integrate search engine with search endpoint
  src/argilla/server/apis/v1/handlers/datasets/records.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/search_engine/base.py
Labels: size:L, lgtm

#4330 fix: add ranking question type explicit properties to search engine mapping
  src/argilla/server/search_engine/commons.py
Labels: type: bug, area: server, language: python, team: backend, size:XS, lgtm

#4327 feat: add new filter support for search records endpoint
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/datasets/records.py
  src/argilla/server/search_engine/base.py
  tests/unit/server/api/v1/datasets/test_search_dataset_records.py
Labels: type: enhancement, area: api, language: python, team: backend, size:L, lgtm

#4332 fix: preserve `TextClassificationSettings.label_schema` order
  CHANGELOG.md
  src/argilla/client/apis/datasets.py
  tests/unit/client/apis/__init__.py
  tests/unit/client/apis/test_datasets.py
Labels: type: bug, language: python, team: backend, area: python sdk, size:M

#4338 docs: Adding `vectors` to a text-classification dataset
  docs/_source/_static/tutorials/end2end/text-classification/argilla-annotation-ui-vectors.png
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-vectors-004.ipynb
  docs/_source/tutorials_and_integrations/tutorials/tutorials.md
Labels: type: documentation, area: ui, size:XL, lgtm

#4326 docs: Update records with `Responses` and `Suggestions`
  docs/_source/_static/tutorials/end2end/text-classification/argilla-annotation-ui-responses.png
  docs/_source/_static/tutorials/end2end/text-classification/argilla-annotation-ui-suggestions.png
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-metadata-003.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-suggestions-and-responses-005.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/train-model-006.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/use-metrics-007.ipynb
  docs/_source/tutorials_and_integrations/tutorials/tutorials.md
Labels: type: documentation, size:XL, lgtm

#4341 bug: fix bug and update test
  src/argilla/client/feedback/utils/assignment.py
  tests/unit/client/feedback/utils/test_assignment.py
Labels: type: bug, area: tests, language: python, team: backend, size:S, lgtm

#4339 feat: update suggestion from record on search engine
  src/argilla/server/apis/v1/handlers/records.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/search_engine/base.py
  src/argilla/server/search_engine/commons.py
  tests/unit/server/api/v1/test_records.py
Labels: type: enhancement, area: api, language: python, team: backend, size:M, lgtm

#4336 feat: delete suggestion from record on search engine
  src/argilla/server/apis/v1/handlers/records.py
  src/argilla/server/apis/v1/handlers/suggestions.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/search_engine/base.py
  src/argilla/server/search_engine/commons.py
  tests/unit/server/api/v1/test_records.py
  tests/unit/server/api/v1/test_suggestions.py
Labels: type: enhancement, area: api, language: python, team: backend, size:M

#4342 docs: example on assigning record to your team for a text classification dataset
  docs/_source/_static/tutorials/end2end/text-classification/group.PNG
  docs/_source/_static/tutorials/end2end/text-classification/group_personal.PNG
  docs/_source/_static/tutorials/end2end/text-classification/individual.PNG
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/assign-records-002.ipynb
  docs/_source/tutorials_and_integrations/tutorials/tutorials.md
Labels: type: documentation, size:XL

#4337 fix: responses and suggestions filter QA
  frontend/assets/scss/abstract/variables/_variables.scss
  frontend/components/feedback-task/container/fields/text-field/TextField.component.vue
  frontend/components/feedback-task/container/questions/form/ranking/drag-and-drop-selection/DndSelection.component.vue
  frontend/components/feedback-task/container/questions/form/text-area/TextArea.component.vue
  frontend/components/feedback-task/header/filters/FilterButton.vue
  frontend/components/feedback-task/header/filters/LabelsSelector.vue
  frontend/v1/domain/entities/metadata/MetadataFilter.ts
  frontend/v1/domain/entities/record/Records.test.ts
  frontend/v1/domain/entities/record/Records.ts
  frontend/v1/domain/entities/response/ResponseFilter.ts
  frontend/v1/domain/entities/suggestion/SuggestionCriteria.ts
  frontend/v1/domain/entities/suggestion/SuggestionFilter.ts
Labels: type: bug, area: ui, language: javascript, size:L, team: frontend

#4348 docs: Tutorial on fine-tuning for a text-classification dataset
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/train-model-006.ipynb
  docs/_source/tutorials_and_integrations/tutorials/tutorials.md
Labels: type: documentation, size:L, lgtm

#4352 Feature/responses operator
  frontend/v1/domain/entities/common/Filter.ts
  frontend/v1/domain/entities/response/ResponseCriteria.test.ts
  frontend/v1/domain/entities/response/ResponseCriteria.ts
  frontend/v1/domain/entities/response/ResponseFilter.ts
  frontend/v1/domain/entities/suggestion/SuggestionCriteria.ts
  frontend/v1/domain/entities/suggestion/SuggestionFilter.ts
  frontend/v1/infrastructure/repositories/RecordRepository.ts
Labels: type: enhancement, area: ui, language: javascript, size:L, team: frontend

#4350 docs: example on filtering and querying records for a text classification dataset
  docs/_source/_static/tutorials/end2end/text-classification/filter-by-metadata.PNG
  docs/_source/_static/tutorials/end2end/text-classification/filter-by-status.PNG
  docs/_source/_static/tutorials/end2end/text-classification/filter_by_fields.PNG
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-metadata-003.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/filter-and-query-008.ipynb
  docs/_source/tutorials_and_integrations/tutorials/tutorials.md
Labels: type: documentation, size:XL, lgtm

#4356 Fix/responses suggestions filter fine tune
  frontend/components/feedback-task/footer/Pagination.component.vue
  frontend/components/feedback-task/header/filters/CategoriesSelector.vue
  frontend/components/feedback-task/header/sort-filter/SortCategoriesList.vue
  frontend/v1/domain/entities/sort/SortList.ts
Labels: area: ui, language: javascript, type: improvement, size:S, team: frontend

#4208 docs: add end2end example on creating a basic text-classification dataset
  .github/workflows/check-repo-files.yml
  .github/workflows/end2end-examples.yml
  .github/workflows/package.yml
  docs/_source/_static/images/llms/fb-model.svg
  docs/_source/_static/tutorials/end2end/base/workflow.drawio
  docs/_source/_static/tutorials/end2end/base/workflow.png
  docs/_source/_static/tutorials/end2end/base/workflow.svg
  docs/_source/_static/tutorials/end2end/base/workflow_add_records.png
  docs/_source/_static/tutorials/end2end/base/workflow_add_records.svg
  docs/_source/_static/tutorials/end2end/base/workflow_assign_records.png
  docs/_source/_static/tutorials/end2end/base/workflow_assign_records.svg
  docs/_source/_static/tutorials/end2end/base/workflow_configure_users.svg
  docs/_source/_static/tutorials/end2end/base/workflow_create_dataset.png
  docs/_source/_static/tutorials/end2end/base/workflow_create_dataset.svg
  docs/_source/_static/tutorials/end2end/base/workflow_metadata.png
  docs/_source/_static/tutorials/end2end/base/workflow_metadata.svg
  docs/_source/_static/tutorials/end2end/base/workflow_metrics.png
  docs/_source/_static/tutorials/end2end/base/workflow_metrics.svg
  docs/_source/_static/tutorials/end2end/base/workflow_sort_and_filter.png
  docs/_source/_static/tutorials/end2end/base/workflow_sort_and_filter.svg
  docs/_source/_static/tutorials/end2end/base/workflow_suggestions_and_responses.png
  docs/_source/_static/tutorials/end2end/base/workflow_suggestions_and_responses.svg
  docs/_source/_static/tutorials/end2end/base/workflow_train_models.png
  docs/_source/_static/tutorials/end2end/base/workflow_train_models.svg
  docs/_source/_static/tutorials/end2end/base/workflow_users_and_workspaces.png
  docs/_source/_static/tutorials/end2end/base/workflow_users_and_workspaces.svg
  docs/_source/_static/tutorials/end2end/base/workflow_vectors.png
  docs/_source/_static/tutorials/end2end/base/workflow_vectors.svg
  docs/_source/_static/tutorials/end2end/text-classification/argilla-annotation-ui-responses.png
  docs/_source/_static/tutorials/end2end/text-classification/argilla-annotation-ui-suggestions.png
  docs/_source/_static/tutorials/end2end/text-classification/argilla-annotation-ui-vectors.png
  docs/_source/_static/tutorials/end2end/text-classification/argilla-ui-page-metadata.png
  docs/_source/_static/tutorials/end2end/text-classification/feedback-dataset-text-classification-1.png
  docs/_source/_static/tutorials/end2end/text-classification/filter-by-metadata.PNG
  docs/_source/_static/tutorials/end2end/text-classification/filter-by-status.PNG
  docs/_source/_static/tutorials/end2end/text-classification/filter_by_fields.PNG
  docs/_source/_static/tutorials/end2end/text-classification/group.PNG
  docs/_source/_static/tutorials/end2end/text-classification/group_personal.PNG
  docs/_source/_static/tutorials/end2end/text-classification/individual.PNG
  docs/_source/conceptual_guides/data_model.md
  docs/_source/getting_started/installation/configurations/user_management.md
  docs/_source/practical_guides/create_dataset.md
  docs/_source/practical_guides/practical_guides.md
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-metadata-003.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-suggestions-and-responses-005.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-vectors-004.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/assign-records-002.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/configure-users-and-workspaces-000.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/create-dataset-001.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/filter-and-query-008.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/train-model-006.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/use-metrics-007.ipynb
  docs/_source/tutorials_and_integrations/tutorials/tutorials.md
  scripts/end2end_examples.py
  src/argilla/client/feedback/utils/assignment.py
Labels: size:XXL

#4355 docs: temporal update to indicate persistent storage
  docs/_source/_static/images/installation/huggingface-spaces/hf-no-persistent-storage.PNG
  docs/_source/_static/images/installation/huggingface-spaces/persistent-storage.PNG
  docs/_source/getting_started/installation/deployments/huggingface-spaces.md
Labels: type: documentation, size:S, lgtm

#4357 chore: update CHANGELOG.md before release v1.20.0
  CHANGELOG.md
Labels: type: documentation, size:S
