Repository argilla-io/argilla, pull requests merged in 2023-03, with the labels that each got.

#2425 Feat/2059 allow passing workspace as client parm for rglog or rgload
  src/argilla/client/api.py
  src/argilla/client/client.py
  tests/client/test_api.py
Labels: enhancement

#2543 Rich print via "[link]" syntax, fixes unresponsive URL in Jupyter Notebooks
  CHANGELOG.md
  src/argilla/client/client.py
Labels: bugfix

#2554 chore: Update "Keep a Changelog" version URL
  CHANGELOG.md
Labels: documentation

#2589 docs: info about rendering images using urls
  docs/_source/guides/query_datasets.md
Labels: documentation
