Repository argilla-io/argilla, pull requests merged in 2023-08, with the labels that each got.

#3462 feat: create user with workspaces
  CHANGELOG.md
  docs/_source/getting_started/installation/configurations/user_management.md
  src/argilla/client/sdk/users/api.py
  src/argilla/client/sdk/users/models.py
  src/argilla/client/users.py
  src/argilla/server/apis/v0/handlers/users.py
  src/argilla/server/contexts/accounts.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/security/model.py
  tests/client/sdk/users/test_api.py
  tests/client/test_users.py
  tests/server/api/v0/test_users.py
Labels: client, api

#3337 feat: delete record endpoint
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/records.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/models/models.py
  src/argilla/server/policies.py
  src/argilla/server/search_engine.py
  tests/unit/server/api/v1/test_records.py
  tests/unit/server/test_search_engine.py
Labels: enhancement, api

#3499 fix: remove `default` from `boolean` values in `argilla_template.md`
  CHANGELOG.md
  src/argilla/client/feedback/integrations/huggingface/card/argilla_template.md
Labels: bugfix

#3502 fix: `DatasetConfig.to_yaml` and `DatasetConfig.from_yaml` to ignore `UUID`
  CHANGELOG.md
  src/argilla/client/feedback/config.py
  tests/unit/client/feedback/conftest.py
  tests/unit/client/feedback/test_config.py
Labels: bugfix

#3506 :sparkles: FEAT : focus on first question on click inside form
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/e2e/annotaion-mode-page/annotation-mode.page.spec.ts
Labels: ui

#3507 feat: environment per PR
  .github/actions/docker-image-tag-from-ref/Dockerfile
  .github/actions/docker-image-tag-from-ref/action.yml
  .github/actions/docker-image-tag-from-ref/app/main.py
  .github/actions/generate-credentials/Dockerfile
  .github/actions/generate-credentials/action.yml
  .github/actions/generate-credentials/app/main.py
  .github/actions/slack-post-credentials/Dockerfile
  .github/actions/slack-post-credentials/action.yml
  .github/actions/slack-post-credentials/app/main.py
  .github/workflows/build-push-docker.yml
  .github/workflows/close-pr.yml
  .github/workflows/deploy-environment.yml
  .github/workflows/package.yml
Labels: ci

#3512 feat: add `delete` method to `FeedbackDataset` in Argilla
  CHANGELOG.md
  src/argilla/client/feedback/dataset/remote.py
  tests/integration/client/feedback/test_dataset.py
Labels: enhancement

#3523 fix: PR message not found
  .github/actions/slack-post-credentials/app/main.py
Labels: bug 🪲, ci

#3539 fix: restore `suggestions` and `responses` as rows in `HuggingFaceDatasetMixin`
  CHANGELOG.md
  docker/scripts/load_data.py
  src/argilla/client/feedback/integrations/huggingface/dataset.py
Labels: client, bugfix

#3547 fix: execute build docker only if build python
  .github/workflows/package.yml
Labels: bug 🪲, ci

#3550 fix: `{FieldSchema, QuestionSchema}.name` attribute didn't have regex validation
  CHANGELOG.md
  src/argilla/client/feedback/schemas/fields.py
  src/argilla/client/feedback/schemas/questions.py
  src/argilla/client/feedback/schemas/validators.py
  tests/unit/client/feedback/schemas/test_fields.py
  tests/unit/client/feedback/schemas/test_questions.py
Labels: bug 🪲, client

#3533 docs: add note regarding the elasticsearch instance to run the tests
  docs/_source/community/developer_docs.md
Labels: documentation

#3567 fix: add missing database `commit`s after `begin_nested`
  CHANGELOG.md
  src/argilla/server/contexts/accounts.py
  src/argilla/server/contexts/datasets.py
Labels: bug 🪲, api

#3575 docs: replace `ELASTICSEARCH` with `ARGILLA_ELASTICSEARCH`
  docs/_source/community/migration-rubrix.md
  docs/_source/conf.py
  docs/_source/getting_started/installation/configurations/elasticsearch.md
  docs/_source/getting_started/installation/deployments/docker.md
  docs/_source/getting_started/installation/deployments/python.md
Labels: documentation

#3571 feat: add delete dataset records endpoint
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/models/mixins.py
  src/argilla/server/policies.py
  src/argilla/server/utils.py
  tests/unit/server/api/v1/test_datasets.py
  tests/unit/server/models/test_base.py
  tests/unit/server/schemas/__init__.py
  tests/unit/server/schemas/test_base.py
Labels: enhancement, api

#3582 feat: add `login` function for storing Argilla credentials
  CHANGELOG.md
  src/argilla/_constants.py
  src/argilla/client/client.py
  src/argilla/client/login.py
  tests/integration/client/test_api.py
  tests/unit/client/test_login.py
Labels: enhancement, client

#3580 feat: update `RemoteFeedbackDataset.delete_records` to use batch endpoint
  CHANGELOG.md
  src/argilla/client/feedback/constants.py
  src/argilla/client/feedback/dataset/remote.py
  src/argilla/client/sdk/commons/models.py
  src/argilla/client/sdk/v1/datasets/api.py
  src/argilla/client/sdk/v1/records/api.py
  src/argilla/client/sdk/v1/users/api.py
  src/argilla/client/sdk/v1/workspaces/api.py
  src/argilla/client/sdk/workspaces/api.py
  tests/integration/client/feedback/dataset/test_remote.py
Labels: enhancement, client

#3601 fix: add `allowed_for_roles` to manage `RemoteFeedbackDataset` permissions
  CHANGELOG.md
  src/argilla/client/feedback/dataset/remote.py
  src/argilla/client/feedback/schemas/records.py
  src/argilla/client/users.py
  src/argilla/client/utils.py
  src/argilla/client/workspaces.py
Labels: bugfix

#3613 feat: add `response_status` param to `GET /api/v1/datasets/{dataset_id}/records`
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/apis/v1/handlers/records.py
  src/argilla/server/contexts/datasets.py
  tests/unit/server/api/v1/test_datasets.py
Labels: enhancement, api

#3608 :sparkles: FEAT: signal required questions instead optional
  frontend/components/commons/forms/questions-form/fields/shared-components/question-header/QuestionHeader.component.vue
  frontend/components/commons/forms/questions-form/fields/shared-components/question-header/questionHeader.component.spec.js
  frontend/e2e/annotation-mode-page/annotation-mode.page.spec.ts
  frontend/plugins/directives/required-field.directive.js
Labels: ui

#3617 feat: add delete suggestions endpoints
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/records.py
  src/argilla/server/apis/v1/handlers/suggestions.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/policies.py
  src/argilla/server/routes.py
  tests/unit/server/api/v1/test_records.py
  tests/unit/server/api/v1/test_suggestions.py
Labels: enhancement, api

#3619 feat: add `list` classmethod to `FeedbackDataset` via `ArgillaMixin`
  CHANGELOG.md
  src/argilla/client/feedback/dataset/local.py
  src/argilla/client/feedback/dataset/mixins.py
  tests/integration/client/feedback/dataset/test_remote.py
Labels: enhancement, client

#3626 fix: `RatingQuestion.values` validation when values out of range
  CHANGELOG.md
  src/argilla/client/feedback/schemas/questions.py
  tests/unit/client/feedback/schemas/test_questions.py
Labels: bugfix

#3467 feat: Allow exporting data for SFT, Reward Modelling (related to RLHF), DPO, rename TrainingTaskMapping
  CHANGELOG.md
  docs/_source/_common/dolly_dataset_info.md
  docs/_source/_common/dolly_dataset_load.md
  docs/_source/_common/snippets/training/feedback-task/text-classification.md
  docs/_source/_common/tabs/train_prepare_for_training.md
  docs/_source/_common/tabs/train_update_config.md
  docs/_source/getting_started/cheatsheet.md
  docs/_source/guides/llms/examples/train-reward-model-rlhf.ipynb
  docs/_source/guides/llms/practical_guides/fine_tune.md
  docs/_source/guides/llms/practical_guides/fine_tune_others.md
  docs/_source/guides/llms/practical_guides/practical_guides.md
  docs/_source/guides/llms/practical_guides/update_dataset.md
  docs/_source/guides/train_a_model.md
  docs/_source/reference/python/python_training.rst
  environment_dev.yml
  pyproject.toml
  src/argilla/client/datasets.py
  src/argilla/client/feedback/__init__.py
  src/argilla/client/feedback/dataset/base.py
  src/argilla/client/feedback/training/__init__.py
  src/argilla/client/feedback/training/base.py
  src/argilla/client/feedback/training/frameworks/transformers.py
  src/argilla/client/feedback/training/frameworks/trl.py
  src/argilla/client/feedback/training/schemas.py
  src/argilla/client/models.py
  src/argilla/feedback/__init__.py
  src/argilla/training/base.py
  src/argilla/training/transformers.py
  tests/integration/client/feedback/test_dataset.py
  tests/integration/client/feedback/training/test_trainer.py
  tests/integration/client/feedback/training/test_trl.py
  tests/integration/training/test_autotrain.py
  tests/unit/client/feedback/training/test_schemas.py
Labels: integration

#3640 fix: remove `TaskType.multi_task_text_token_classification`
  CHANGELOG.md
  src/argilla/client/sdk/datasets/models.py
  src/argilla/server/commons/models.py
Labels: bugfix

#3638 feat: add `rg.list_datasets` for API v0 datasets
  CHANGELOG.md
  src/argilla/__init__.py
  src/argilla/client/api.py
  src/argilla/client/client.py
  src/argilla/client/sdk/datasets/api.py
  tests/database.py
  tests/integration/client/sdk/api/test_datasets.py
Labels: enhancement

#3621 :bug: FIX : Regex for query search highlight
  frontend/plugins/plugins/highlight-search.js
Labels: bug 🪲

#3623 fix: response with `draft` status was returning `422`
  src/argilla/server/contexts/datasets.py
  src/argilla/server/models/questions.py
  src/argilla/server/schemas/v1/responses.py
  tests/unit/server/api/v1/test_records.py
  tests/unit/server/api/v1/test_responses.py
Labels: api, bugfix

#3641 fix: add `list_workspaces` under `rg.*` and fix some type-hints
  CHANGELOG.md
  src/argilla/__init__.py
  src/argilla/client/api.py
  src/argilla/client/client.py
Labels: enhancement, bugfix

#3651 feat: add `RemoteFeedbackRecord.delete_suggestions` and `RemoteSuggestionSchema.delete`
  CHANGELOG.md
  docs/_source/guides/llms/practical_guides/update_dataset.md
  src/argilla/client/feedback/dataset/mixins.py
  src/argilla/client/feedback/dataset/remote/base.py
  src/argilla/client/feedback/schemas/records.py
  src/argilla/client/sdk/v1/records/api.py
  src/argilla/client/sdk/v1/suggestions/__init__.py
  src/argilla/client/sdk/v1/suggestions/api.py
  src/argilla/client/sdk/v1/suggestions/models.py
  tests/integration/client/feedback/schemas/test_records.py
  tests/integration/client/feedback/test_dataset.py
  tests/integration/client/sdk/v1/__init__.py
  tests/integration/client/sdk/v1/test_datasets.py
  tests/integration/client/sdk/v1/test_records.py
  tests/integration/client/sdk/v1/test_suggestions.py
  tests/integration/client/sdk/v1/test_users.py
  tests/integration/client/sdk/v1/test_workspaces.py
  tests/unit/client/sdk/models/v1/test_suggestions.py
Labels: enhancement, client

#3663 chore: deprecation lifecycle before 1.15.0
  CHANGELOG.md
  src/argilla/client/feedback/dataset/base.py
  src/argilla/client/feedback/dataset/local.py
  src/argilla/client/feedback/dataset/mixins.py
  src/argilla/client/feedback/dataset/remote/base.py
  src/argilla/client/feedback/dataset/remote/dataset.py
  src/argilla/client/feedback/schemas/records.py
  tests/integration/client/feedback/schemas/test_records.py
  tests/integration/client/feedback/test_dataset.py
  tests/unit/client/feedback/schemas/test_records.py
Labels: client, deprecation

#3671 feat: add `users delete` command
  CHANGELOG.md
  src/argilla/client/users.py
  src/argilla/tasks/users/__main__.py
  src/argilla/tasks/users/delete.py
  tests/unit/tasks/users/conftest.py
  tests/unit/tasks/users/test_create.py
  tests/unit/tasks/users/test_delete.py
Labels: enhancement, cli

#3688 feat: add `users list` command
  CHANGELOG.md
  src/argilla/tasks/datasets/list.py
  src/argilla/tasks/users/__main__.py
  src/argilla/tasks/users/create.py
  src/argilla/tasks/users/list.py
  src/argilla/tasks/whoami/__main__.py
  tests/unit/tasks/conftest.py
  tests/unit/tasks/datasets/test_list.py
  tests/unit/tasks/users/conftest.py
  tests/unit/tasks/users/test_delete.py
  tests/unit/tasks/users/test_list.py
Labels: enhancement, cli

#3684 docs: Remove pre-training section & rename fine_tune docs
  docs/_source/guides/llms/practical_guides/fine_tune.md
Labels: documentation
