Repository argilla-io/argilla, pull requests merged in 2023-05, with the labels that each got.

#2812 feat : show next record after submit discard
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/feedback-task/footer/Pagination.component.vue
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
  frontend/components/page-contents/feedback-task-content/dataset-settings/LeftDatasetSettingsFeedbackTask.content.vue
  frontend/models/feedback-task-model/feedback-dataset/FeedbackDataset.model.js
  frontend/models/feedback-task-model/record/record.queries.js
Labels: ui

#2813 feat : optional tag for questions
  frontend/components/commons/forms/questions-form/fields/mono-selection/MonoSelection.component.vue
  frontend/components/commons/forms/questions-form/fields/text-area/TextArea.component.vue
  frontend/nuxt.config.js
  frontend/plugins/custom-directives/optional-field.directive.js
Labels: ui

#2802 [docs] Update broken imports, code & links
  docs/_source/guides/programmatic_labeling_with_rules.ipynb
Labels: documentation

#2829 fix: pagination synchronisation on change params
  frontend/components/feedback-task/footer/Pagination.component.vue
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
Labels: ui

#2833 Feat : allow discarding/clear a record from user
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/components/text2text/results/Text2TextContentEditable.vue
  frontend/models/feedback-task-model/record-response/recordResponse.queries.js
  frontend/models/feedback-task-model/record/Record.model.js
  frontend/models/feedback-task-model/record/record.queries.js
Labels: ui

#2860 fix : init default value for responses with no value
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
Labels: bug 🪲, ui

#2890 fix : synchronous problem when one record in dataset
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
Labels: bug 🪲, ui

#2891 feat : update toast messages
  frontend/components/feedback-task/footer/PaginationFeedbackTask.component.vue
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
  frontend/pages/dataset/_id/annotation-mode/index.vue
Labels: ui

#2899 Fix: fix typo to get current page logic works
  frontend/components/feedback-task/footer/Pagination.component.vue
  frontend/components/feedback-task/footer/PaginationFeedbackTask.component.vue
Labels: bug 🪲, ui

#2898 feat: Remove searchbar and show empty guidelines in dataset settings
  frontend/components/feedback-task/DatasetFilters.component.vue
  frontend/components/page-contents/feedback-task-content/dataset-settings/LeftDatasetSettingsFeedbackTask.content.vue
Labels: ui

#2916 Feat/updates styles metrics sidebar panel
  frontend/components/commons/sidebar-feedback-task/SidebarFeedbackTask.component.vue
  frontend/components/commons/sidebar-feedback-task/SidebarFeedbackTaskProgress.vue
  frontend/components/feedback-task/FeedbackTaskProgress.vue
  frontend/models/feedback-task-model/dataset-metric/DatasetMetric.model.js
Labels: ui

#2933 Style: small fixes for Feedback Task
  frontend/components/commons/dataset-description/DatasetDescription.component.vue
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/commons/forms/questions-form/fields/mono-selection/MonoSelection.component.vue
  frontend/components/commons/sidebar-feedback-task/SidebarFeedbackTask.component.vue
  frontend/components/commons/sidebar-feedback-task/SidebarFeedbackTaskProgress.vue
  frontend/components/feedback-task/RecordFeedbackTask.component.vue
  frontend/components/feedback-task/feedbackTask.properties.js
  frontend/components/feedback-task/field/TextField.component.vue
  frontend/components/feedback-task/footer/PaginationFeedbackTask.component.vue
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
  frontend/pages/dataset/_id/annotation-mode/index.vue
Labels: ui

#2943 List all the `FeedbackDataset` responses not just the current user's
  src/argilla/client/sdk/v1/datasets/api.py
Labels: bugfix

#2964 feat : show toast on switch route
  frontend/pages/dataset/_id/annotation-mode/index.vue
Labels: ui

#2979 Refactor : Stop using total records in front end
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/feedback-task/DatasetFilters.component.vue
  frontend/components/feedback-task/StatusFilter.vue
  frontend/components/feedback-task/footer/Pagination.component.vue
  frontend/components/feedback-task/footer/PaginationFeedbackTask.component.vue
  frontend/components/page-contents/feedback-task-content/CenterFeedbackTask.content.vue
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/models/feedback-task-model/feedback-dataset/FeedbackDataset.model.js
  frontend/models/feedback-task-model/feedback-dataset/feedbackDataset.queries.js
  frontend/models/feedback-task-model/record/record.queries.js
  src/argilla/client/sdk/v1/datasets/models.py
  src/argilla/server/apis/v1/handlers/datasets.py
  src/argilla/server/schemas/v1/datasets.py
  tests/server/api/v1/test_datasets.py
Labels: ui

#2992 fix : missmatch status on navigation
  .codecov.yml
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/models/feedback-task-model/record-field/recordField.queries.js
  frontend/models/feedback-task-model/record-response/recordResponse.queries.js
Labels: bug 🪲, ui

#2997 :bug: reinitiate flag onDestroy hook
  frontend/components/commons/forms/questions-form/QuestionsForm.component.vue
  frontend/components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue
Labels: bug 🪲

#3005 feat: add single label selection question to the API
  src/argilla/server/models/questions.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/search_engine.py
  tests/factories.py
  tests/server/api/v1/test_datasets.py
  tests/server/api/v1/test_records.py
Labels: enhancement, api

#3009 :bug: fix logout when questionnaire have been touched
  frontend/pages/dataset/_id/annotation-mode/index.vue
Labels: bug 🪲, ui

#3020 Add example in `add_records` docstring & fix issue in `FeedbackDataset` docstring
  src/argilla/client/feedback.py
Labels: documentation

#3032 fix: `logging.warning` printing multiple times & `from_huggingface` minor fixes
  scripts/load_data.py
  src/argilla/client/feedback.py
Labels: bugfix

#3015 Fix function-args retrieval and file-deletion after train
  docs/_source/community/developer_docs.md
  src/argilla/training/setfit.py
  src/argilla/training/utils.py
  tests/training/helpers.py
Labels: bugfix

#3010 feat: add multi label selection question to the API
  CHANGELOG.md
  src/argilla/server/models/questions.py
  src/argilla/server/schemas/v1/datasets.py
  src/argilla/server/search_engine.py
  tests/factories.py
  tests/server/api/v1/test_datasets.py
  tests/server/api/v1/test_records.py
Labels: enhancement, api

#3038 refactor: `FeedbackDataset.records` are now `FeedbackRecord` instead of Python `dict`
  src/argilla/client/feedback.py
  src/argilla/client/sdk/v1/datasets/api.py
  tests/client/sdk/v1/datasets/test_api.py
  tests/client/test_feedback.py
Labels: breaking changes
