Repository argilla-io/argilla, pull requests merged in 2023-12, with the labels that each got.

#4368 docs: extend using proxy section
  docker/nginx/docker-compose.yaml
  docker/nginx/nginx.conf
  docker/traefik/docker-compose.yaml
  docs/_source/getting_started/installation/configurations/server_configuration.md
Labels: type: documentation, area: server, size:M

#4379 docs: hugging face space url
  docs/_source/getting_started/installation/deployments/huggingface-spaces.md
  docs/_source/getting_started/quickstart_installation.ipynb
  docs/_source/tutorials/notebooks/deploying-text2text-dvc-explainability.ipynb
  docs/_source/tutorials/notebooks/deploying-texttokenclassification-fastapi.ipynb
  docs/_source/tutorials/notebooks/labelling-spacy-llm.ipynb
  docs/_source/tutorials/notebooks/labelling-text2text-disaggregators-explainability.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-gpt3-fewshot.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-sentence-transformers-semantic.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-sentencetransformers-semantic.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-sentencetransformers-weaksupervision.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-setfit-zeroshot.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-sklearn-weaksupervision.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-snorkel-weaksupervision.ipynb
  docs/_source/tutorials/notebooks/labelling-tokenclassification-basics.ipynb
  docs/_source/tutorials/notebooks/labelling-tokenclassification-deletelabels.ipynb
  docs/_source/tutorials/notebooks/labelling-tokenclassification-flair-fewshot.ipynb
  docs/_source/tutorials/notebooks/labelling-tokenclassification-skweak-weaksupervision.ipynb
  docs/_source/tutorials/notebooks/labelling-tokenclassification-spacy-pretrained.ipynb
  docs/_source/tutorials/notebooks/labelling-tokenclassification-using-spacy-llm.ipynb
  docs/_source/tutorials/notebooks/making-most-of-markdown.ipynb
  docs/_source/tutorials/notebooks/monitoring-textclassification-cleanlab-explainability.ipynb
  docs/_source/tutorials/notebooks/monitoring-textclassification-setfit-explainability.ipynb
  docs/_source/tutorials/notebooks/monitoring-textclassification-shaptransformersinterpret-explainability.ipynb
  docs/_source/tutorials/notebooks/monitoring-textclassification-transformers-explainability.ipynb
  docs/_source/tutorials/notebooks/ner_fine_tune_bert_beginners.ipynb
  docs/_source/tutorials/notebooks/training-textclassification-classyclassification-activelearning.ipynb
  docs/_source/tutorials/notebooks/training-textclassification-modal-activelearning.ipynb
  docs/_source/tutorials/notebooks/training-textclassification-setfit-fewshot.ipynb
  docs/_source/tutorials/notebooks/training-textclassification-setfit-sentiment.ipynb
  docs/_source/tutorials/notebooks/training-textclassification-smalltext-activelearning.ipynb
  docs/_source/tutorials/notebooks/training-textclassification-transformers-pretrained.ipynb
  docs/_source/tutorials/notebooks/training-textgeneration-unstructured.ipynb
  docs/_source/tutorials_and_integrations/integrations/process_documents_with_unstructured.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/curating-feedback-instructiondataset.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/fine-tuning-openai-rag-feedback.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/fine-tuning-sentencesimilarity-rag.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/labelling-feedback-langchain-syntethic.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/labelling-feedback-setfit.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/labelling-spacy-llm.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/train-reward-model-rlhf.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/trainer-feedback-setfit.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/training-llm-mistral-sft.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/training-qa-transformers.ipynb
  docs/_source/tutorials_and_integrations/tutorials/other_datasets/few_shot_learning_with_setfit.ipynb
  docs/_source/tutorials_and_integrations/tutorials/other_datasets/few_shot_text_classification_with_active_learning.ipynb
  docs/_source/tutorials_and_integrations/tutorials/other_datasets/label_data_with_semantic_search.ipynb
  docs/_source/tutorials_and_integrations/tutorials/other_datasets/label_errors_cleanlab.ipynb
  docs/_source/tutorials_and_integrations/tutorials/other_datasets/labelling-tokenclassification-using-spacy-llm.ipynb
  docs/_source/tutorials_and_integrations/tutorials/other_datasets/weak_supervision_ner.ipynb
  docs/_source/tutorials_and_integrations/tutorials/other_datasets/weak_supervision_text_classification_semantic_search.ipynb
Labels: type: documentation, size:M, lgtm, area: ux

#4384 fix: Fix typo in `SuggestionsMetric`
  src/argilla/client/feedback/dataset/mixins.py
  src/argilla/client/feedback/metrics/__init__.py
Labels: type: bug, language: python, team: backend, area: python sdk, size:XS

#4393 Token Classification epochs parameter trainer changed
  docs/_source/practical_guides/fine_tune.md
Labels: type: documentation, area: trainer, team: ml, size:XS, lgtm

#4392 Fixing typo in Fine Tuning LLMs Practical Guides
  docs/_source/practical_guides/fine_tune.md
Labels: type: documentation, team: ml, size:XS, lgtm, status: invalid

#4376 docs: add making most of markdown to tutorial page
  docs/_source/getting_started/installation/configurations/image_support.md
  docs/_source/tutorials_and_integrations/tutorials/feedback/making-most-of-markdown.ipynb
  docs/_source/tutorials_and_integrations/tutorials/tutorials.md
Labels: type: documentation, area: architecture, size:XS, lgtm

#4395 fix: pinning `pytest-asyncio` to version `0.21.1` to avoid problems running unit tests on GitHub workflows
  environment_dev.yml
Labels: type: bug, area: tests, area: ci, type: dependencies, language: python, team: backend, size:XS, lgtm

#4363 docs: add faq files
  README.md
  docs/_source/getting_started/argilla.md
Labels: type: documentation, area: architecture, size:L, lgtm

#4362 ✨ Fix error handling in axios plugin for 401
  CHANGELOG.md
  frontend/plugins/plugins/axios.ts
  frontend/translation/en.json
Labels: size:S, lgtm

#4083 feat: create default `text_descriptives` as metadata via `utils.modeling` module (#4017)
  environment_dev.yml
  pyproject.toml
  src/argilla/client/feedback/integrations/textdescriptives_.py
  tests/unit/client/feedback/integrations/test_textdescriptives_.py
Labels: type: enhancement, area: tests, type: integration, type: dependencies, language: python, team: backend, area: python sdk, size:XL

#4402 docs: Improve info in `metrics` section
  docs/_source/practical_guides/collect_responses.md
Labels: size:L, lgtm

#4405 ✨ Improve you are online
  frontend/layouts/app.vue
  frontend/translation/en.json
Labels: area: ui, language: javascript, type: improvement, size:S, lgtm, team: frontend

#4409 feat: Align the docstrings with new `metrics` classification
  src/argilla/client/feedback/metrics/annotator_metrics.py
Labels: size:S, lgtm

#4397 fix: Fix `prepare_dataset_for_annotation_task` to return correct format
  src/argilla/client/feedback/metrics/agreement_metrics.py
  tests/integration/client/feedback/metrics/test_agreement_metrics.py
Labels: type: bug, status: help wanted, language: python, team: backend, area: python sdk, size:XS, lgtm

#4380 feat: add endpoint to create responses for current user in bulk
  CHANGELOG.md
  src/argilla/server/apis/v1/handlers/responses.py
  src/argilla/server/contexts/datasets.py
  src/argilla/server/models/database.py
  src/argilla/server/models/mixins.py
  src/argilla/server/schemas/v1/responses.py
  tests/unit/server/api/v1/responses/__init__.py
  tests/unit/server/api/v1/responses/test_create_current_user_responses_bulk.py
Labels: type: enhancement, status: help wanted, area: server, area: tests, area: api, language: python, team: backend, size:XL, lgtm

#4423 feat: change bulk responses items limit from 50 to 100
  src/argilla/server/schemas/v1/responses.py
  tests/unit/server/api/v1/responses/test_create_current_user_responses_bulk.py
Labels: type: enhancement, area: api, language: python, team: backend, size:XS

#4425 docs: Fix links and outputs in end2end tutorials
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-metadata-003.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-suggestions-and-responses-005.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-vectors-004.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/assign-records-002.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/configure-users-and-workspaces-000.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/create-dataset-001.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/filter-and-query-008.ipynb
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/train-model-006.ipynb
Labels: type: documentation, area: ui, team: ml, size:XL, lgtm, status: invalid

#4422 fix: Correct naming of the fields for RAG in TaskTemplates
  docs/_source/_common/tabs/task_templates.md
  docs/_source/tutorials_and_integrations/tutorials/feedback/fine-tuning-sentencesimilarity-rag.ipynb
  src/argilla/client/feedback/dataset/local/mixins.py
Labels: type: bug, language: python, team: backend, area: python sdk, size:S, lgtm, status: invalid

#4428 ✨ Improve cache for max age without value
  frontend/plugins/plugins/axios-cache.ts
Labels: area: ui, language: javascript, type: improvement, size:S, lgtm, team: frontend

#4215 ⌨️ feat: improve keyboard navigation
  docs/_source/_common/shortcuts.md
  frontend/components/base/base-range/BaseRangeMultipleSlider.vue
  frontend/components/feedback-task/container/questions/QuestionsForm.component.vue
  frontend/components/feedback-task/container/questions/form/Questions.component.vue
  frontend/components/feedback-task/container/questions/form/multi-label/MultiLabel.component.vue
  frontend/components/feedback-task/container/questions/form/ranking/drag-and-drop-selection/DndSelection.component.vue
  frontend/components/feedback-task/container/questions/form/rating/RatingShortcuts.vue
  frontend/components/feedback-task/container/questions/form/shared-components/label-selection/LabelSelection.component.vue
  frontend/components/feedback-task/container/questions/form/shared-components/search-label/SearchLabel.component.vue
  frontend/components/feedback-task/container/questions/form/single-label/SingleLabel.component.vue
  frontend/components/feedback-task/container/questions/form/text-area/ContentEditableFeedbackTask.vue
  frontend/components/feedback-task/container/questions/form/text-area/TextAreaContents.vue
  frontend/components/feedback-task/container/questions/form/useQuestionsViewModel.ts
  frontend/components/feedback-task/footer/Pagination.component.vue
  frontend/components/feedback-task/header/SearchBar.base.vue
  frontend/components/feedback-task/header/filters/LabelsSelectorSearch.vue
  frontend/components/feedback-task/sidebar/HelpShortcut.vue
  frontend/translation/en.json
  frontend/v1/domain/entities/record/Records.test.ts
  frontend/v1/infrastructure/services/useLocalStorage.ts
  frontend/v1/store/create.ts
Labels: area: ui, type: improvement, size:L, area: ux, team: frontend

#4412 feat: Add tests and docs for deprecated `unify_responses` method
  docs/_source/practical_guides/collect_responses.md
  src/argilla/client/feedback/metrics/annotator_metrics.py
  tests/integration/client/feedback/metrics/test_annotator_metrics.py
  tests/integration/client/feedback/test_unification.py
Labels: status: question, area: tests, language: python, type: deprecation, team: backend, size:L, lgtm

#4424 🐛 Fix total items on pagination
  CHANGELOG.md
  frontend/components/feedback-task/container/RecordFeedbackTaskAndQuestionnaire.content.vue
  frontend/components/feedback-task/container/useRecordFeedbackTaskViewModel.ts
  frontend/v1/domain/entities/record/Records.test.ts
  frontend/v1/domain/entities/record/Records.ts
  frontend/v1/domain/services/IRecordStorage.ts
  frontend/v1/domain/usecases/load-records-to-annotate-use-case.ts
  frontend/v1/infrastructure/storage/RecordsStorage.ts
Labels: type: bug, status: wontfix, area: ui, language: javascript, size:L, lgtm, team: frontend

#4400 feat: create default `text_descriptives` as metadata via `utils.modeling`
  CHANGELOG.md
  docs/_source/practical_guides/annotation_workflows/annotation_workflows.md
  docs/_source/practical_guides/create_update_dataset/create_dataset.md
  docs/_source/practical_guides/create_update_dataset/metadata.md
  environment_dev.yml
  pyproject.toml
  src/argilla/client/feedback/integrations/textdescriptives.py
  tests/unit/client/feedback/integrations/test_textdescriptives_.py
Labels: type: documentation, type: enhancement, area: tests, type: integration, language: python, team: backend, area: python sdk, size:XL

#4434 fix: prepare bulk and shortcuts QA
  frontend/assets/scss/abstract/variables/_variables.scss
  frontend/components/feedback-task/container/fields/RecordFieldsAndSimilarity.vue
  frontend/components/feedback-task/container/questions/QuestionsForm.component.vue
  frontend/translation/en.json
Labels: status: wontfix, area: ui, language: javascript, type: improvement, size:M, team: frontend

#4436 ✨ Use delay just when the component has two or more coincidences, and…
  frontend/components/feedback-task/container/questions/form/rating/RatingShortcuts.vue
  frontend/components/feedback-task/container/questions/form/shared-components/label-selection/LabelSelection.component.vue
  frontend/components/feedback-task/header/sort-filter/SortSelector.vue
Labels: status: question, area: ui, language: javascript, type: improvement, size:M, lgtm, team: frontend

#4439 docs: Update documentation on metadata allowing for aggregate values
  docs/_source/practical_guides/create_update_dataset/metadata.md
  docs/_source/practical_guides/create_update_dataset/records.md
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-metadata-003.ipynb
Labels: type: documentation, area: api, team: backend, size:L, lgtm, status: invalid

#4414 feature: Add list like aggregation support for metadata
  CHANGELOG.md
  docs/_source/practical_guides/create_update_dataset/metadata.md
  docs/_source/practical_guides/create_update_dataset/records.md
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/add-metadata-003.ipynb
  src/argilla/client/feedback/constants.py
  src/argilla/client/feedback/schemas/metadata.py
  src/argilla/server/models/metadata_properties.py
  tests/unit/server/api/v1/test_records.py
Labels: language: python, team: backend, type: improvement, area: python sdk, size:L, lgtm

#4441 feat: add `httpx_extra_kwargs` argument to `init`
  CHANGELOG.md
  frontend/plugins/logo/index.ts
  src/argilla/client/client.py
  src/argilla/client/sdk/client.py
  src/argilla/client/singleton.py
Labels: size:M

#4398 docs: UI improve no dataset page to transform it into an onboarding page for first time users developers
  docs/_source/_common/snippets/start_page.md
  docs/_source/getting_started/quickstart_workflow.ipynb
  docs/_source/getting_started/quickstart_workflow_feedback.ipynb
  frontend/components/features/datasets/datasets-table/datasets-empty/DatasetsEmpty.vue
  frontend/static/images/logo.svg
  scripts/end2end_examples.py
Labels: type: documentation, area: ui, size:L

#4444 bug/Update textdescriptives.py
  src/argilla/client/feedback/integrations/textdescriptives.py
Labels: type: breaking changes, language: python, team: backend, area: python sdk, size:XS

#4271 feat: add metrics module aligned with unification
  CHANGELOG.md
  docs/_source/_common/tabs/unfication_strategies.md
  docs/_source/practical_guides/collect_responses.md
  docs/_source/reference/python/index.rst
  docs/_source/reference/python/python_annotation_metrics.rst
  docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/use-metrics-007.ipynb
  docs/_source/tutorials_and_integrations/tutorials/tutorials.md
  src/argilla/client/feedback/dataset/base.py
  src/argilla/client/feedback/dataset/local/dataset.py
  src/argilla/client/feedback/dataset/mixins.py
  src/argilla/client/feedback/dataset/remote/dataset.py
  src/argilla/client/feedback/metrics/__init__.py
  src/argilla/client/feedback/metrics/agreement_metrics.py
  src/argilla/client/feedback/metrics/annotator_metrics.py
  src/argilla/client/feedback/metrics/base.py
  src/argilla/client/feedback/metrics/utils.py
  src/argilla/client/feedback/training/schemas/base.py
  src/argilla/client/feedback/unification.py
  tests/integration/client/conftest.py
  tests/integration/client/feedback/dataset/remote/test_dataset.py
  tests/integration/client/feedback/metrics/__init__.py
  tests/integration/client/feedback/metrics/test_agreement_metrics.py
  tests/integration/client/feedback/metrics/test_annotator_metrics.py
  tests/integration/client/feedback/metrics/test_utils.py
  tests/integration/client/feedback/test_unification.py
Labels: size:XXL

#4433 refactor: align backend response status with UI
  CHANGELOG.md
  frontend/e2e/common/metadata-api-mock.ts
  frontend/e2e/common/record-api-mock.ts
  frontend/v1/infrastructure/repositories/RecordRepository.ts
  src/argilla/server/enums.py
  src/argilla/server/search_engine/base.py
  src/argilla/server/search_engine/commons.py
  tests/unit/server/api/v1/test_list_dataset_records.py
Labels: area: server, language: python, type: refactor, team: backend, size:M, lgtm, status: invalid

#4432 refactor: Review server app setup
  src/argilla/__init__.py
  src/argilla/server/app.py
  src/argilla/server/server.py
  tests/integration/conftest.py
  tests/unit/server/conftest.py
  tests/unit/server/test_server_app.py
Labels: area: server, language: python, type: refactor, team: backend, size:XL, lgtm, status: invalid

#4426 refactor: review security module
  src/argilla/cli/server/database/users/migrate.py
  src/argilla/server/app.py
  src/argilla/server/contexts/accounts.py
  src/argilla/server/security/__init__.py
  src/argilla/server/security/auth_provider/__init__.py
  src/argilla/server/security/auth_provider/base.py
  src/argilla/server/security/auth_provider/db/__init__.py
  src/argilla/server/security/auth_provider/db/provider.py
  src/argilla/server/security/auth_provider/db/settings.py
  src/argilla/server/server.py
  tests/integration/client/feedback/dataset/remote/test_dataset.py
  tests/unit/cli/server/database/users/test_migrate.py
  tests/unit/server/security/test_provider.py
Labels: area: server, language: python, type: refactor, team: backend, size:L, lgtm
