Repository argilla-io/argilla, pull requests merged in 2023-01, with the labels that each got.

#2128 added gpt3 and setfit tutorials to resolve messy PR branches
  docs/_source/_static/tutorials/labelling-textclassification-gpt3-fewshot/labelling-textclassification-gpt3-fewshot-1.png
  docs/_source/_static/tutorials/labelling-textclassification-gpt3-fewshot/labelling-textclassification-gpt3-fewshot-2.png
  docs/_source/_static/tutorials/labelling-textclassification-gpt3-fewshot/labelling-textclassification-gpt3-fewshot-3.png
  docs/_source/_static/tutorials/labelling-textclassification-gpt3-fewshot/modal.md
  docs/_source/_static/tutorials/labelling-tokenclassification-flair-fewshot/modal.md
  docs/_source/_static/tutorials/training-textclassification-setfit-fewshot/modal.md
  docs/_source/_static/tutorials/training-textclassification-setfit-sentiment/modal.md
  docs/_source/_static/tutorials/training-textclassification-setfit-sentiment/setfit_sentiment.png
  docs/_source/tutorials/libraries/classyclassification.md
  docs/_source/tutorials/libraries/libraries.md
  docs/_source/tutorials/libraries/openai.md
  docs/_source/tutorials/libraries/setfit.md
  docs/_source/tutorials/notebooks/labelling-textclassification-gpt3-fewshot.ipynb
  docs/_source/tutorials/notebooks/training-textclassification-setfit-sentiment.ipynb
  docs/_source/tutorials/steps/1_labelling.md
  docs/_source/tutorials/steps/2_training.md
  docs/_source/tutorials/tasks/text_classification.md
  docs/_source/tutorials/techniques/explainability.md
  docs/_source/tutorials/techniques/few_shot.md
Labels: documentation

#2129 initial version of the disaggregators tutorial
  docs/_source/_static/tutorials/labelling-text2text-disaggregators-explainability/labelling-text2text-disaggregators-explainability.png
  docs/_source/_static/tutorials/labelling-text2text-disaggregators-explainability/labelling-text2text-disaggregators-explainability_ui.png
  docs/_source/_static/tutorials/labelling-text2text-disaggregators-explainability/labelling-text2text-disaggregators-explainability_ui_record.png
  docs/_source/_static/tutorials/labelling-text2text-disaggregators-explainability/modal.md
  docs/_source/tutorials/libraries/disaggregators.md
  docs/_source/tutorials/libraries/libraries.md
  docs/_source/tutorials/notebooks/labelling-text2text-disaggregators-explainability.ipynb
  docs/_source/tutorials/notebooks/labelling-textclassification-sentencetransformers-weaksupervision.ipynb
  docs/_source/tutorials/notebooks/training-textclassification-classyclassification-activelearning.ipynb
  docs/_source/tutorials/notebooks/training-textclassification-modal-activelearning.ipynb
  docs/_source/tutorials/steps/1_labelling.md
  docs/_source/tutorials/tasks/text_generation.md
  docs/_source/tutorials/techniques/explainability.md
Labels: documentation

#2136 docs: reverted to correct apikey reference
  docs/_source/getting_started/installation/user_management.md
  src/argilla/client/api.py
Labels: documentation

#2146 # 2085 added more explicit error message if no records are being passed
  src/argilla/labeling/text_classification/label_models.py
Labels: api

#2211 fix(Client): Stop using `ujson` for client actions
  src/argilla/client/sdk/client.py
  src/argilla/server/daos/backend/generic_elastic.py
Labels: client, bugfix

#2243 refactor: Remove final slash for the list datasets endpoint
  src/argilla/server/apis/v0/handlers/datasets.py
  src/argilla/server/apis/v0/helpers.py
Labels: technical debt, server, api

#2248 perf: Load data in chunks
  src/argilla/client/apis/datasets.py
  src/argilla/client/client.py
  src/argilla/client/sdk/text2text/api.py
  src/argilla/client/sdk/text_classification/api.py
  src/argilla/client/sdk/text_classification/models.py
  src/argilla/client/sdk/token_classification/api.py
  src/argilla/server/apis/v0/handlers/text2text.py
  src/argilla/server/apis/v0/handlers/text_classification.py
  src/argilla/server/apis/v0/handlers/token_classification.py
  src/argilla/server/daos/backend/client_adapters/opensearch.py
  src/argilla/server/daos/backend/search/query_builder.py
  tests/client/sdk/text2text/test_api.py
  tests/client/sdk/text_classification/test_api.py
  tests/client/sdk/token_classification/test_api.py
Labels: enhancement
