Repository argilla-io/argilla, pull requests merged in 2024-02, with the labels that each got.

#4560 Docs: bulk actions for filtered results
  docs/_source/practical_guides/annotate_dataset.md
Labels: type: documentation, size:XS

#4562 feat: add more telemetry metrics
  docs/_source/reference/telemetry.md
  src/argilla/server/apis/v0/handlers/users.py
  src/argilla/server/apis/v1/handlers/oauth2.py
  src/argilla/server/telemetry.py
  src/argilla/server/utils/_telemetry.py
  tests/unit/server/commons/test_telemetry.py
Labels: area: server, language: python, team: backend, type: improvement, size:L, lgtm

#4565 update HF welcome page and sign-in copy
  frontend/pages/sign-in.vue
  frontend/translation/en.js
Labels: area: ui, language: javascript, type: improvement, size:XS, team: frontend

#4564 docs: basic auth with HF
  docs/_source/getting_started/installation/deployments/huggingface-spaces.md
Labels: type: documentation, team: backend, size:M

#4563 docs: extend scrollable area in sidebar
  docs/_source/_static/css/custom.css
Labels: type: bug, size:S, area: ux, team: frontend

#4561 feat: Show full label titles in form
  frontend/components/feedback-task/container/questions/form/shared-components/label-selection/LabelSelection.component.vue
Labels: type: enhancement, area: ui, language: javascript, size:S, lgtm, team: frontend

#4576 docs: update Azure and add GCP documentation for quickstart deployment
  docs/_source/getting_started/installation/deployments/cloud_providers.md
Labels: type: documentation, size:L

#4569 feat: improve description tooltip
  frontend/components/base/base-badge/BaseBadge.vue
  frontend/components/feedback-task/settings/SettingsFields.vue
  frontend/components/feedback-task/settings/SettingsMetadata.vue
  frontend/plugins/directives/tooltip.directive.js
Labels: area: ui, language: javascript, type: improvement, size:L, lgtm, team: frontend

#4579 feat: responsive ui
  .github/workflows/deploy-environment.yml
  frontend/assets/scss/abstract/placeholders/_placeholders.scss
  frontend/assets/scss/base/base.scss
  frontend/components/base/base-breadcrumbs/BaseBreadcrumbs.vue
  frontend/components/base/base-tooltip/BaseTooltip.vue
  frontend/components/base/base-topbar-brand/BaseTopbarBrand.vue
  frontend/components/commons/header/header-feedback-task/HeaderFeedbackTask.component.vue
  frontend/components/commons/sidebar/SidebarMenu.vue
  frontend/components/features/datasets/datasets-table/DatasetsTable.vue
  frontend/components/feedback-task/container/fields/Record.vue
  frontend/components/feedback-task/container/mode/BulkAnnotation.vue
  frontend/components/feedback-task/container/mode/FocusAnnotation.vue
  frontend/components/feedback-task/container/questions/QuestionsForm.component.vue
  frontend/components/feedback-task/header/DatasetFilters.component.vue
  frontend/components/feedback-task/settings/SettingsInfo.vue
  frontend/components/feedback-task/settings/SettingsInfoReadOnly.vue
  frontend/components/feedback-task/sidebar/SidebarFeedbackTask.component.vue
  frontend/layouts/HeaderAndOneColumn.vue
  frontend/layouts/HeaderAndTopAndOneColumn.vue
  frontend/pages/dataset/_id/settings.vue
  frontend/pages/datasets/index.vue
  frontend/pages/sign-in.vue
  frontend/plugins/directives/tooltip.directive.js
Labels: type: enhancement, area: ui, language: javascript, size:L, team: frontend

#4582 😬 missing g
  docs/_source/getting_started/installation/deployments/deployments.md
Labels: type: documentation, size:XS, lgtm

#4580 docs: review argilla server dev references
  docs/_source/community/developer_docs.md
  docs/_source/getting_started/installation/configurations/server_configuration.md
Labels: type: documentation, area: server, language: python, team: backend, size:S

#4578 feat: ignore deploying preview environment for fork PRs
  .github/workflows/close-pr.yml
  .github/workflows/package.yml
Labels: area: ci, team: backend, type: improvement, size:S, lgtm

#4504 Update cloud_providers.md - added GCP instructions
  docs/_source/getting_started/installation/deployments/cloud_providers.md
Labels: type: documentation, team: backend, size:XS, lgtm

#4571 docs: update example in hf spaces page
  docs/_source/getting_started/installation/deployments/huggingface-spaces.md
Labels: type: documentation, team: ml, size:L, lgtm

#4538 ☁️ Sign cloud support
  frontend/components/base/base-button/BaseButton.vue
  frontend/jest.setup.ts
  frontend/playwright.config.ts
  frontend/plugins/plugins/axios.ts
  frontend/translation/en.js
  frontend/v1/infrastructure/services/useRoutes.ts
Labels: type: enhancement, area: ui, language: javascript, size:L, team: frontend

#4601 fix: check integration tests failure
  environment_dev.yml
  pyproject.toml
  tests/integration/conftest.py
Labels: type: bug, area: tests, language: python, team: backend, size:S, lgtm

#4598 🏷️ Feat/reorder labels
  CHANGELOG.md
  frontend/components/feedback-task/container/questions/form/shared-components/label-selection/LabelSelection.component.vue
  frontend/components/feedback-task/settings/SettingsQuestions.vue
  frontend/translation/en.js
  frontend/v1/domain/entities/question/Question.ts
  frontend/v1/infrastructure/repositories/QuestionRepository.ts
Labels: type: enhancement, area: ui, language: javascript, size:L, team: frontend

#4602 4533 remove support for missing response status
  CHANGELOG.md
  docs/_source/practical_guides/filter_dataset.md
  src/argilla/client/feedback/schemas/enums.py
  src/argilla/client/sdk/v1/datasets/api.py
  src/argilla/client/sdk/v1/datasets/models.py
  tests/integration/client/feedback/dataset/remote/test_filter_and_sorting.py
Labels: language: python, type: refactor, team: backend, area: python sdk, size:S, lgtm

#4605 bug: FloatMetadataProperty: value is not a valid float when it is an rounded integer
  CHANGELOG.md
  src/argilla/client/feedback/integrations/textdescriptives.py
  tests/integration/client/feedback/integrations/huggingface/test_model_card.py
Labels: type: bug, team: backend, area: python sdk, size:S, lgtm

#4600 feat: relax pandas constraint version to allow for >2.0
  .github/workflows/run-python-tests.yml
  CHANGELOG.md
  environment_dev.yml
  pyproject.toml
  tests/integration/client/feedback/integrations/huggingface/test_model_card.py
Labels: language: python, team: backend, type: improvement, area: python sdk, size:S, lgtm

#4609 chore: resolved faulty redirect in empty dataset landing
  CHANGELOG.md
  docs/_source/_common/snippets/start_page.md
Labels: type: documentation, area: ui, size:XS, lgtm, team: frontend

#4588 docs: update company positioning
  README.md
Labels: size:L

#4610 docs: include references about how to reindex datasets in hf spaces
  docs/_source/getting_started/installation/configurations/database_migrations.md
  docs/_source/getting_started/installation/deployments/deployments.md
  docs/_source/getting_started/installation/deployments/docker-quickstart.md
Labels: type: documentation, team: backend, size:S, lgtm

#4614 bug: fix bug when running integrations tests for text descriptives
  src/argilla/client/feedback/integrations/textdescriptives.py
Labels: type: bug, area: tests, language: python, team: backend, size:S, lgtm, severity: minor
